
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
 * This file exports the `Deal` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Deal
 * 
 */
export type DealModel = runtime.Types.Result.DefaultSelection<Prisma.$DealPayload>

export type AggregateDeal = {
  _count: DealCountAggregateOutputType | null
  _avg: DealAvgAggregateOutputType | null
  _sum: DealSumAggregateOutputType | null
  _min: DealMinAggregateOutputType | null
  _max: DealMaxAggregateOutputType | null
}

export type DealAvgAggregateOutputType = {
  id: number | null
  gameId: number | null
  price: number | null
  discountPercent: number | null
  originalPrice: number | null
  rating: number | null
}

export type DealSumAggregateOutputType = {
  id: number | null
  gameId: number | null
  price: number | null
  discountPercent: number | null
  originalPrice: number | null
  rating: number | null
}

export type DealMinAggregateOutputType = {
  id: number | null
  gameId: number | null
  title: string | null
  storeName: string | null
  price: number | null
  discountPercent: number | null
  originalPrice: number | null
  url: string | null
  validFrom: Date | null
  validUntil: Date | null
  isFreebie: boolean | null
  discoveredAt: Date | null
  updatedAt: Date | null
  externalId: string | null
  source: string | null
  thumb: string | null
  rating: number | null
}

export type DealMaxAggregateOutputType = {
  id: number | null
  gameId: number | null
  title: string | null
  storeName: string | null
  price: number | null
  discountPercent: number | null
  originalPrice: number | null
  url: string | null
  validFrom: Date | null
  validUntil: Date | null
  isFreebie: boolean | null
  discoveredAt: Date | null
  updatedAt: Date | null
  externalId: string | null
  source: string | null
  thumb: string | null
  rating: number | null
}

export type DealCountAggregateOutputType = {
  id: number
  gameId: number
  title: number
  storeName: number
  price: number
  discountPercent: number
  originalPrice: number
  url: number
  validFrom: number
  validUntil: number
  isFreebie: number
  discoveredAt: number
  updatedAt: number
  externalId: number
  source: number
  thumb: number
  rating: number
  _all: number
}


export type DealAvgAggregateInputType = {
  id?: true
  gameId?: true
  price?: true
  discountPercent?: true
  originalPrice?: true
  rating?: true
}

export type DealSumAggregateInputType = {
  id?: true
  gameId?: true
  price?: true
  discountPercent?: true
  originalPrice?: true
  rating?: true
}

export type DealMinAggregateInputType = {
  id?: true
  gameId?: true
  title?: true
  storeName?: true
  price?: true
  discountPercent?: true
  originalPrice?: true
  url?: true
  validFrom?: true
  validUntil?: true
  isFreebie?: true
  discoveredAt?: true
  updatedAt?: true
  externalId?: true
  source?: true
  thumb?: true
  rating?: true
}

export type DealMaxAggregateInputType = {
  id?: true
  gameId?: true
  title?: true
  storeName?: true
  price?: true
  discountPercent?: true
  originalPrice?: true
  url?: true
  validFrom?: true
  validUntil?: true
  isFreebie?: true
  discoveredAt?: true
  updatedAt?: true
  externalId?: true
  source?: true
  thumb?: true
  rating?: true
}

export type DealCountAggregateInputType = {
  id?: true
  gameId?: true
  title?: true
  storeName?: true
  price?: true
  discountPercent?: true
  originalPrice?: true
  url?: true
  validFrom?: true
  validUntil?: true
  isFreebie?: true
  discoveredAt?: true
  updatedAt?: true
  externalId?: true
  source?: true
  thumb?: true
  rating?: true
  _all?: true
}

export type DealAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Deal to aggregate.
   */
  where?: Prisma.DealWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Deals to fetch.
   */
  orderBy?: Prisma.DealOrderByWithRelationInput | Prisma.DealOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DealWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Deals from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Deals.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Deals
  **/
  _count?: true | DealCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DealAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DealSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DealMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DealMaxAggregateInputType
}

export type GetDealAggregateType<T extends DealAggregateArgs> = {
      [P in keyof T & keyof AggregateDeal]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDeal[P]>
    : Prisma.GetScalarType<T[P], AggregateDeal[P]>
}




export type DealGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DealWhereInput
  orderBy?: Prisma.DealOrderByWithAggregationInput | Prisma.DealOrderByWithAggregationInput[]
  by: Prisma.DealScalarFieldEnum[] | Prisma.DealScalarFieldEnum
  having?: Prisma.DealScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DealCountAggregateInputType | true
  _avg?: DealAvgAggregateInputType
  _sum?: DealSumAggregateInputType
  _min?: DealMinAggregateInputType
  _max?: DealMaxAggregateInputType
}

export type DealGroupByOutputType = {
  id: number
  gameId: number | null
  title: string
  storeName: string
  price: number | null
  discountPercent: number | null
  originalPrice: number | null
  url: string
  validFrom: Date | null
  validUntil: Date | null
  isFreebie: boolean
  discoveredAt: Date
  updatedAt: Date
  externalId: string | null
  source: string | null
  thumb: string | null
  rating: number | null
  _count: DealCountAggregateOutputType | null
  _avg: DealAvgAggregateOutputType | null
  _sum: DealSumAggregateOutputType | null
  _min: DealMinAggregateOutputType | null
  _max: DealMaxAggregateOutputType | null
}

type GetDealGroupByPayload<T extends DealGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DealGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DealGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DealGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DealGroupByOutputType[P]>
      }
    >
  > 



export type DealWhereInput = {
  AND?: Prisma.DealWhereInput | Prisma.DealWhereInput[]
  OR?: Prisma.DealWhereInput[]
  NOT?: Prisma.DealWhereInput | Prisma.DealWhereInput[]
  id?: Prisma.IntFilter<"Deal"> | number
  gameId?: Prisma.IntNullableFilter<"Deal"> | number | null
  title?: Prisma.StringFilter<"Deal"> | string
  storeName?: Prisma.StringFilter<"Deal"> | string
  price?: Prisma.FloatNullableFilter<"Deal"> | number | null
  discountPercent?: Prisma.FloatNullableFilter<"Deal"> | number | null
  originalPrice?: Prisma.FloatNullableFilter<"Deal"> | number | null
  url?: Prisma.StringFilter<"Deal"> | string
  validFrom?: Prisma.DateTimeNullableFilter<"Deal"> | Date | string | null
  validUntil?: Prisma.DateTimeNullableFilter<"Deal"> | Date | string | null
  isFreebie?: Prisma.BoolFilter<"Deal"> | boolean
  discoveredAt?: Prisma.DateTimeFilter<"Deal"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Deal"> | Date | string
  externalId?: Prisma.StringNullableFilter<"Deal"> | string | null
  source?: Prisma.StringNullableFilter<"Deal"> | string | null
  thumb?: Prisma.StringNullableFilter<"Deal"> | string | null
  rating?: Prisma.FloatNullableFilter<"Deal"> | number | null
  game?: Prisma.XOR<Prisma.GameNullableScalarRelationFilter, Prisma.GameWhereInput> | null
  wishlist_deal_notifications?: Prisma.Wishlist_deal_notificationsListRelationFilter
}

export type DealOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  gameId?: Prisma.SortOrderInput | Prisma.SortOrder
  title?: Prisma.SortOrder
  storeName?: Prisma.SortOrder
  price?: Prisma.SortOrderInput | Prisma.SortOrder
  discountPercent?: Prisma.SortOrderInput | Prisma.SortOrder
  originalPrice?: Prisma.SortOrderInput | Prisma.SortOrder
  url?: Prisma.SortOrder
  validFrom?: Prisma.SortOrderInput | Prisma.SortOrder
  validUntil?: Prisma.SortOrderInput | Prisma.SortOrder
  isFreebie?: Prisma.SortOrder
  discoveredAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  externalId?: Prisma.SortOrderInput | Prisma.SortOrder
  source?: Prisma.SortOrderInput | Prisma.SortOrder
  thumb?: Prisma.SortOrderInput | Prisma.SortOrder
  rating?: Prisma.SortOrderInput | Prisma.SortOrder
  game?: Prisma.GameOrderByWithRelationInput
  wishlist_deal_notifications?: Prisma.wishlist_deal_notificationsOrderByRelationAggregateInput
}

export type DealWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  deal_external_unique?: Prisma.DealDeal_external_uniqueCompoundUniqueInput
  AND?: Prisma.DealWhereInput | Prisma.DealWhereInput[]
  OR?: Prisma.DealWhereInput[]
  NOT?: Prisma.DealWhereInput | Prisma.DealWhereInput[]
  gameId?: Prisma.IntNullableFilter<"Deal"> | number | null
  title?: Prisma.StringFilter<"Deal"> | string
  storeName?: Prisma.StringFilter<"Deal"> | string
  price?: Prisma.FloatNullableFilter<"Deal"> | number | null
  discountPercent?: Prisma.FloatNullableFilter<"Deal"> | number | null
  originalPrice?: Prisma.FloatNullableFilter<"Deal"> | number | null
  url?: Prisma.StringFilter<"Deal"> | string
  validFrom?: Prisma.DateTimeNullableFilter<"Deal"> | Date | string | null
  validUntil?: Prisma.DateTimeNullableFilter<"Deal"> | Date | string | null
  isFreebie?: Prisma.BoolFilter<"Deal"> | boolean
  discoveredAt?: Prisma.DateTimeFilter<"Deal"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Deal"> | Date | string
  externalId?: Prisma.StringNullableFilter<"Deal"> | string | null
  source?: Prisma.StringNullableFilter<"Deal"> | string | null
  thumb?: Prisma.StringNullableFilter<"Deal"> | string | null
  rating?: Prisma.FloatNullableFilter<"Deal"> | number | null
  game?: Prisma.XOR<Prisma.GameNullableScalarRelationFilter, Prisma.GameWhereInput> | null
  wishlist_deal_notifications?: Prisma.Wishlist_deal_notificationsListRelationFilter
}, "id" | "deal_external_unique">

export type DealOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  gameId?: Prisma.SortOrderInput | Prisma.SortOrder
  title?: Prisma.SortOrder
  storeName?: Prisma.SortOrder
  price?: Prisma.SortOrderInput | Prisma.SortOrder
  discountPercent?: Prisma.SortOrderInput | Prisma.SortOrder
  originalPrice?: Prisma.SortOrderInput | Prisma.SortOrder
  url?: Prisma.SortOrder
  validFrom?: Prisma.SortOrderInput | Prisma.SortOrder
  validUntil?: Prisma.SortOrderInput | Prisma.SortOrder
  isFreebie?: Prisma.SortOrder
  discoveredAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  externalId?: Prisma.SortOrderInput | Prisma.SortOrder
  source?: Prisma.SortOrderInput | Prisma.SortOrder
  thumb?: Prisma.SortOrderInput | Prisma.SortOrder
  rating?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.DealCountOrderByAggregateInput
  _avg?: Prisma.DealAvgOrderByAggregateInput
  _max?: Prisma.DealMaxOrderByAggregateInput
  _min?: Prisma.DealMinOrderByAggregateInput
  _sum?: Prisma.DealSumOrderByAggregateInput
}

export type DealScalarWhereWithAggregatesInput = {
  AND?: Prisma.DealScalarWhereWithAggregatesInput | Prisma.DealScalarWhereWithAggregatesInput[]
  OR?: Prisma.DealScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DealScalarWhereWithAggregatesInput | Prisma.DealScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Deal"> | number
  gameId?: Prisma.IntNullableWithAggregatesFilter<"Deal"> | number | null
  title?: Prisma.StringWithAggregatesFilter<"Deal"> | string
  storeName?: Prisma.StringWithAggregatesFilter<"Deal"> | string
  price?: Prisma.FloatNullableWithAggregatesFilter<"Deal"> | number | null
  discountPercent?: Prisma.FloatNullableWithAggregatesFilter<"Deal"> | number | null
  originalPrice?: Prisma.FloatNullableWithAggregatesFilter<"Deal"> | number | null
  url?: Prisma.StringWithAggregatesFilter<"Deal"> | string
  validFrom?: Prisma.DateTimeNullableWithAggregatesFilter<"Deal"> | Date | string | null
  validUntil?: Prisma.DateTimeNullableWithAggregatesFilter<"Deal"> | Date | string | null
  isFreebie?: Prisma.BoolWithAggregatesFilter<"Deal"> | boolean
  discoveredAt?: Prisma.DateTimeWithAggregatesFilter<"Deal"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Deal"> | Date | string
  externalId?: Prisma.StringNullableWithAggregatesFilter<"Deal"> | string | null
  source?: Prisma.StringNullableWithAggregatesFilter<"Deal"> | string | null
  thumb?: Prisma.StringNullableWithAggregatesFilter<"Deal"> | string | null
  rating?: Prisma.FloatNullableWithAggregatesFilter<"Deal"> | number | null
}

export type DealCreateInput = {
  title: string
  storeName: string
  price?: number | null
  discountPercent?: number | null
  originalPrice?: number | null
  url: string
  validFrom?: Date | string | null
  validUntil?: Date | string | null
  isFreebie?: boolean
  discoveredAt?: Date | string
  updatedAt?: Date | string
  externalId?: string | null
  source?: string | null
  thumb?: string | null
  rating?: number | null
  game?: Prisma.GameCreateNestedOneWithoutDealsInput
  wishlist_deal_notifications?: Prisma.wishlist_deal_notificationsCreateNestedManyWithoutDealsInput
}

export type DealUncheckedCreateInput = {
  id?: number
  gameId?: number | null
  title: string
  storeName: string
  price?: number | null
  discountPercent?: number | null
  originalPrice?: number | null
  url: string
  validFrom?: Date | string | null
  validUntil?: Date | string | null
  isFreebie?: boolean
  discoveredAt?: Date | string
  updatedAt?: Date | string
  externalId?: string | null
  source?: string | null
  thumb?: string | null
  rating?: number | null
  wishlist_deal_notifications?: Prisma.wishlist_deal_notificationsUncheckedCreateNestedManyWithoutDealsInput
}

export type DealUpdateInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  storeName?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  discountPercent?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  originalPrice?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  url?: Prisma.StringFieldUpdateOperationsInput | string
  validFrom?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  validUntil?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isFreebie?: Prisma.BoolFieldUpdateOperationsInput | boolean
  discoveredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  externalId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  thumb?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rating?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  game?: Prisma.GameUpdateOneWithoutDealsNestedInput
  wishlist_deal_notifications?: Prisma.wishlist_deal_notificationsUpdateManyWithoutDealsNestedInput
}

export type DealUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  gameId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  storeName?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  discountPercent?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  originalPrice?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  url?: Prisma.StringFieldUpdateOperationsInput | string
  validFrom?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  validUntil?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isFreebie?: Prisma.BoolFieldUpdateOperationsInput | boolean
  discoveredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  externalId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  thumb?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rating?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  wishlist_deal_notifications?: Prisma.wishlist_deal_notificationsUncheckedUpdateManyWithoutDealsNestedInput
}

export type DealCreateManyInput = {
  id?: number
  gameId?: number | null
  title: string
  storeName: string
  price?: number | null
  discountPercent?: number | null
  originalPrice?: number | null
  url: string
  validFrom?: Date | string | null
  validUntil?: Date | string | null
  isFreebie?: boolean
  discoveredAt?: Date | string
  updatedAt?: Date | string
  externalId?: string | null
  source?: string | null
  thumb?: string | null
  rating?: number | null
}

export type DealUpdateManyMutationInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  storeName?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  discountPercent?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  originalPrice?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  url?: Prisma.StringFieldUpdateOperationsInput | string
  validFrom?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  validUntil?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isFreebie?: Prisma.BoolFieldUpdateOperationsInput | boolean
  discoveredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  externalId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  thumb?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rating?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
}

export type DealUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  gameId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  storeName?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  discountPercent?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  originalPrice?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  url?: Prisma.StringFieldUpdateOperationsInput | string
  validFrom?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  validUntil?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isFreebie?: Prisma.BoolFieldUpdateOperationsInput | boolean
  discoveredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  externalId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  thumb?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rating?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
}

export type DealListRelationFilter = {
  every?: Prisma.DealWhereInput
  some?: Prisma.DealWhereInput
  none?: Prisma.DealWhereInput
}

export type DealOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type DealDeal_external_uniqueCompoundUniqueInput = {
  externalId: string
  source: string
}

export type DealCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  gameId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  storeName?: Prisma.SortOrder
  price?: Prisma.SortOrder
  discountPercent?: Prisma.SortOrder
  originalPrice?: Prisma.SortOrder
  url?: Prisma.SortOrder
  validFrom?: Prisma.SortOrder
  validUntil?: Prisma.SortOrder
  isFreebie?: Prisma.SortOrder
  discoveredAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  externalId?: Prisma.SortOrder
  source?: Prisma.SortOrder
  thumb?: Prisma.SortOrder
  rating?: Prisma.SortOrder
}

export type DealAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  gameId?: Prisma.SortOrder
  price?: Prisma.SortOrder
  discountPercent?: Prisma.SortOrder
  originalPrice?: Prisma.SortOrder
  rating?: Prisma.SortOrder
}

export type DealMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  gameId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  storeName?: Prisma.SortOrder
  price?: Prisma.SortOrder
  discountPercent?: Prisma.SortOrder
  originalPrice?: Prisma.SortOrder
  url?: Prisma.SortOrder
  validFrom?: Prisma.SortOrder
  validUntil?: Prisma.SortOrder
  isFreebie?: Prisma.SortOrder
  discoveredAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  externalId?: Prisma.SortOrder
  source?: Prisma.SortOrder
  thumb?: Prisma.SortOrder
  rating?: Prisma.SortOrder
}

export type DealMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  gameId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  storeName?: Prisma.SortOrder
  price?: Prisma.SortOrder
  discountPercent?: Prisma.SortOrder
  originalPrice?: Prisma.SortOrder
  url?: Prisma.SortOrder
  validFrom?: Prisma.SortOrder
  validUntil?: Prisma.SortOrder
  isFreebie?: Prisma.SortOrder
  discoveredAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  externalId?: Prisma.SortOrder
  source?: Prisma.SortOrder
  thumb?: Prisma.SortOrder
  rating?: Prisma.SortOrder
}

export type DealSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  gameId?: Prisma.SortOrder
  price?: Prisma.SortOrder
  discountPercent?: Prisma.SortOrder
  originalPrice?: Prisma.SortOrder
  rating?: Prisma.SortOrder
}

export type DealScalarRelationFilter = {
  is?: Prisma.DealWhereInput
  isNot?: Prisma.DealWhereInput
}

export type DealCreateNestedManyWithoutGameInput = {
  create?: Prisma.XOR<Prisma.DealCreateWithoutGameInput, Prisma.DealUncheckedCreateWithoutGameInput> | Prisma.DealCreateWithoutGameInput[] | Prisma.DealUncheckedCreateWithoutGameInput[]
  connectOrCreate?: Prisma.DealCreateOrConnectWithoutGameInput | Prisma.DealCreateOrConnectWithoutGameInput[]
  createMany?: Prisma.DealCreateManyGameInputEnvelope
  connect?: Prisma.DealWhereUniqueInput | Prisma.DealWhereUniqueInput[]
}

export type DealUncheckedCreateNestedManyWithoutGameInput = {
  create?: Prisma.XOR<Prisma.DealCreateWithoutGameInput, Prisma.DealUncheckedCreateWithoutGameInput> | Prisma.DealCreateWithoutGameInput[] | Prisma.DealUncheckedCreateWithoutGameInput[]
  connectOrCreate?: Prisma.DealCreateOrConnectWithoutGameInput | Prisma.DealCreateOrConnectWithoutGameInput[]
  createMany?: Prisma.DealCreateManyGameInputEnvelope
  connect?: Prisma.DealWhereUniqueInput | Prisma.DealWhereUniqueInput[]
}

export type DealUpdateManyWithoutGameNestedInput = {
  create?: Prisma.XOR<Prisma.DealCreateWithoutGameInput, Prisma.DealUncheckedCreateWithoutGameInput> | Prisma.DealCreateWithoutGameInput[] | Prisma.DealUncheckedCreateWithoutGameInput[]
  connectOrCreate?: Prisma.DealCreateOrConnectWithoutGameInput | Prisma.DealCreateOrConnectWithoutGameInput[]
  upsert?: Prisma.DealUpsertWithWhereUniqueWithoutGameInput | Prisma.DealUpsertWithWhereUniqueWithoutGameInput[]
  createMany?: Prisma.DealCreateManyGameInputEnvelope
  set?: Prisma.DealWhereUniqueInput | Prisma.DealWhereUniqueInput[]
  disconnect?: Prisma.DealWhereUniqueInput | Prisma.DealWhereUniqueInput[]
  delete?: Prisma.DealWhereUniqueInput | Prisma.DealWhereUniqueInput[]
  connect?: Prisma.DealWhereUniqueInput | Prisma.DealWhereUniqueInput[]
  update?: Prisma.DealUpdateWithWhereUniqueWithoutGameInput | Prisma.DealUpdateWithWhereUniqueWithoutGameInput[]
  updateMany?: Prisma.DealUpdateManyWithWhereWithoutGameInput | Prisma.DealUpdateManyWithWhereWithoutGameInput[]
  deleteMany?: Prisma.DealScalarWhereInput | Prisma.DealScalarWhereInput[]
}

export type DealUncheckedUpdateManyWithoutGameNestedInput = {
  create?: Prisma.XOR<Prisma.DealCreateWithoutGameInput, Prisma.DealUncheckedCreateWithoutGameInput> | Prisma.DealCreateWithoutGameInput[] | Prisma.DealUncheckedCreateWithoutGameInput[]
  connectOrCreate?: Prisma.DealCreateOrConnectWithoutGameInput | Prisma.DealCreateOrConnectWithoutGameInput[]
  upsert?: Prisma.DealUpsertWithWhereUniqueWithoutGameInput | Prisma.DealUpsertWithWhereUniqueWithoutGameInput[]
  createMany?: Prisma.DealCreateManyGameInputEnvelope
  set?: Prisma.DealWhereUniqueInput | Prisma.DealWhereUniqueInput[]
  disconnect?: Prisma.DealWhereUniqueInput | Prisma.DealWhereUniqueInput[]
  delete?: Prisma.DealWhereUniqueInput | Prisma.DealWhereUniqueInput[]
  connect?: Prisma.DealWhereUniqueInput | Prisma.DealWhereUniqueInput[]
  update?: Prisma.DealUpdateWithWhereUniqueWithoutGameInput | Prisma.DealUpdateWithWhereUniqueWithoutGameInput[]
  updateMany?: Prisma.DealUpdateManyWithWhereWithoutGameInput | Prisma.DealUpdateManyWithWhereWithoutGameInput[]
  deleteMany?: Prisma.DealScalarWhereInput | Prisma.DealScalarWhereInput[]
}

export type DealCreateNestedOneWithoutWishlist_deal_notificationsInput = {
  create?: Prisma.XOR<Prisma.DealCreateWithoutWishlist_deal_notificationsInput, Prisma.DealUncheckedCreateWithoutWishlist_deal_notificationsInput>
  connectOrCreate?: Prisma.DealCreateOrConnectWithoutWishlist_deal_notificationsInput
  connect?: Prisma.DealWhereUniqueInput
}

export type DealUpdateOneRequiredWithoutWishlist_deal_notificationsNestedInput = {
  create?: Prisma.XOR<Prisma.DealCreateWithoutWishlist_deal_notificationsInput, Prisma.DealUncheckedCreateWithoutWishlist_deal_notificationsInput>
  connectOrCreate?: Prisma.DealCreateOrConnectWithoutWishlist_deal_notificationsInput
  upsert?: Prisma.DealUpsertWithoutWishlist_deal_notificationsInput
  connect?: Prisma.DealWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.DealUpdateToOneWithWhereWithoutWishlist_deal_notificationsInput, Prisma.DealUpdateWithoutWishlist_deal_notificationsInput>, Prisma.DealUncheckedUpdateWithoutWishlist_deal_notificationsInput>
}

export type DealCreateWithoutGameInput = {
  title: string
  storeName: string
  price?: number | null
  discountPercent?: number | null
  originalPrice?: number | null
  url: string
  validFrom?: Date | string | null
  validUntil?: Date | string | null
  isFreebie?: boolean
  discoveredAt?: Date | string
  updatedAt?: Date | string
  externalId?: string | null
  source?: string | null
  thumb?: string | null
  rating?: number | null
  wishlist_deal_notifications?: Prisma.wishlist_deal_notificationsCreateNestedManyWithoutDealsInput
}

export type DealUncheckedCreateWithoutGameInput = {
  id?: number
  title: string
  storeName: string
  price?: number | null
  discountPercent?: number | null
  originalPrice?: number | null
  url: string
  validFrom?: Date | string | null
  validUntil?: Date | string | null
  isFreebie?: boolean
  discoveredAt?: Date | string
  updatedAt?: Date | string
  externalId?: string | null
  source?: string | null
  thumb?: string | null
  rating?: number | null
  wishlist_deal_notifications?: Prisma.wishlist_deal_notificationsUncheckedCreateNestedManyWithoutDealsInput
}

export type DealCreateOrConnectWithoutGameInput = {
  where: Prisma.DealWhereUniqueInput
  create: Prisma.XOR<Prisma.DealCreateWithoutGameInput, Prisma.DealUncheckedCreateWithoutGameInput>
}

export type DealCreateManyGameInputEnvelope = {
  data: Prisma.DealCreateManyGameInput | Prisma.DealCreateManyGameInput[]
  skipDuplicates?: boolean
}

export type DealUpsertWithWhereUniqueWithoutGameInput = {
  where: Prisma.DealWhereUniqueInput
  update: Prisma.XOR<Prisma.DealUpdateWithoutGameInput, Prisma.DealUncheckedUpdateWithoutGameInput>
  create: Prisma.XOR<Prisma.DealCreateWithoutGameInput, Prisma.DealUncheckedCreateWithoutGameInput>
}

export type DealUpdateWithWhereUniqueWithoutGameInput = {
  where: Prisma.DealWhereUniqueInput
  data: Prisma.XOR<Prisma.DealUpdateWithoutGameInput, Prisma.DealUncheckedUpdateWithoutGameInput>
}

export type DealUpdateManyWithWhereWithoutGameInput = {
  where: Prisma.DealScalarWhereInput
  data: Prisma.XOR<Prisma.DealUpdateManyMutationInput, Prisma.DealUncheckedUpdateManyWithoutGameInput>
}

export type DealScalarWhereInput = {
  AND?: Prisma.DealScalarWhereInput | Prisma.DealScalarWhereInput[]
  OR?: Prisma.DealScalarWhereInput[]
  NOT?: Prisma.DealScalarWhereInput | Prisma.DealScalarWhereInput[]
  id?: Prisma.IntFilter<"Deal"> | number
  gameId?: Prisma.IntNullableFilter<"Deal"> | number | null
  title?: Prisma.StringFilter<"Deal"> | string
  storeName?: Prisma.StringFilter<"Deal"> | string
  price?: Prisma.FloatNullableFilter<"Deal"> | number | null
  discountPercent?: Prisma.FloatNullableFilter<"Deal"> | number | null
  originalPrice?: Prisma.FloatNullableFilter<"Deal"> | number | null
  url?: Prisma.StringFilter<"Deal"> | string
  validFrom?: Prisma.DateTimeNullableFilter<"Deal"> | Date | string | null
  validUntil?: Prisma.DateTimeNullableFilter<"Deal"> | Date | string | null
  isFreebie?: Prisma.BoolFilter<"Deal"> | boolean
  discoveredAt?: Prisma.DateTimeFilter<"Deal"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Deal"> | Date | string
  externalId?: Prisma.StringNullableFilter<"Deal"> | string | null
  source?: Prisma.StringNullableFilter<"Deal"> | string | null
  thumb?: Prisma.StringNullableFilter<"Deal"> | string | null
  rating?: Prisma.FloatNullableFilter<"Deal"> | number | null
}

export type DealCreateWithoutWishlist_deal_notificationsInput = {
  title: string
  storeName: string
  price?: number | null
  discountPercent?: number | null
  originalPrice?: number | null
  url: string
  validFrom?: Date | string | null
  validUntil?: Date | string | null
  isFreebie?: boolean
  discoveredAt?: Date | string
  updatedAt?: Date | string
  externalId?: string | null
  source?: string | null
  thumb?: string | null
  rating?: number | null
  game?: Prisma.GameCreateNestedOneWithoutDealsInput
}

export type DealUncheckedCreateWithoutWishlist_deal_notificationsInput = {
  id?: number
  gameId?: number | null
  title: string
  storeName: string
  price?: number | null
  discountPercent?: number | null
  originalPrice?: number | null
  url: string
  validFrom?: Date | string | null
  validUntil?: Date | string | null
  isFreebie?: boolean
  discoveredAt?: Date | string
  updatedAt?: Date | string
  externalId?: string | null
  source?: string | null
  thumb?: string | null
  rating?: number | null
}

export type DealCreateOrConnectWithoutWishlist_deal_notificationsInput = {
  where: Prisma.DealWhereUniqueInput
  create: Prisma.XOR<Prisma.DealCreateWithoutWishlist_deal_notificationsInput, Prisma.DealUncheckedCreateWithoutWishlist_deal_notificationsInput>
}

export type DealUpsertWithoutWishlist_deal_notificationsInput = {
  update: Prisma.XOR<Prisma.DealUpdateWithoutWishlist_deal_notificationsInput, Prisma.DealUncheckedUpdateWithoutWishlist_deal_notificationsInput>
  create: Prisma.XOR<Prisma.DealCreateWithoutWishlist_deal_notificationsInput, Prisma.DealUncheckedCreateWithoutWishlist_deal_notificationsInput>
  where?: Prisma.DealWhereInput
}

export type DealUpdateToOneWithWhereWithoutWishlist_deal_notificationsInput = {
  where?: Prisma.DealWhereInput
  data: Prisma.XOR<Prisma.DealUpdateWithoutWishlist_deal_notificationsInput, Prisma.DealUncheckedUpdateWithoutWishlist_deal_notificationsInput>
}

export type DealUpdateWithoutWishlist_deal_notificationsInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  storeName?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  discountPercent?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  originalPrice?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  url?: Prisma.StringFieldUpdateOperationsInput | string
  validFrom?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  validUntil?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isFreebie?: Prisma.BoolFieldUpdateOperationsInput | boolean
  discoveredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  externalId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  thumb?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rating?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  game?: Prisma.GameUpdateOneWithoutDealsNestedInput
}

export type DealUncheckedUpdateWithoutWishlist_deal_notificationsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  gameId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  title?: Prisma.StringFieldUpdateOperationsInput | string
  storeName?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  discountPercent?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  originalPrice?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  url?: Prisma.StringFieldUpdateOperationsInput | string
  validFrom?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  validUntil?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isFreebie?: Prisma.BoolFieldUpdateOperationsInput | boolean
  discoveredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  externalId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  thumb?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rating?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
}

export type DealCreateManyGameInput = {
  id?: number
  title: string
  storeName: string
  price?: number | null
  discountPercent?: number | null
  originalPrice?: number | null
  url: string
  validFrom?: Date | string | null
  validUntil?: Date | string | null
  isFreebie?: boolean
  discoveredAt?: Date | string
  updatedAt?: Date | string
  externalId?: string | null
  source?: string | null
  thumb?: string | null
  rating?: number | null
}

export type DealUpdateWithoutGameInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  storeName?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  discountPercent?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  originalPrice?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  url?: Prisma.StringFieldUpdateOperationsInput | string
  validFrom?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  validUntil?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isFreebie?: Prisma.BoolFieldUpdateOperationsInput | boolean
  discoveredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  externalId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  thumb?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rating?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  wishlist_deal_notifications?: Prisma.wishlist_deal_notificationsUpdateManyWithoutDealsNestedInput
}

export type DealUncheckedUpdateWithoutGameInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  storeName?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  discountPercent?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  originalPrice?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  url?: Prisma.StringFieldUpdateOperationsInput | string
  validFrom?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  validUntil?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isFreebie?: Prisma.BoolFieldUpdateOperationsInput | boolean
  discoveredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  externalId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  thumb?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rating?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  wishlist_deal_notifications?: Prisma.wishlist_deal_notificationsUncheckedUpdateManyWithoutDealsNestedInput
}

export type DealUncheckedUpdateManyWithoutGameInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  storeName?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  discountPercent?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  originalPrice?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  url?: Prisma.StringFieldUpdateOperationsInput | string
  validFrom?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  validUntil?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isFreebie?: Prisma.BoolFieldUpdateOperationsInput | boolean
  discoveredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  externalId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  thumb?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  rating?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
}


/**
 * Count Type DealCountOutputType
 */

export type DealCountOutputType = {
  wishlist_deal_notifications: number
}

export type DealCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  wishlist_deal_notifications?: boolean | DealCountOutputTypeCountWishlist_deal_notificationsArgs
}

/**
 * DealCountOutputType without action
 */
export type DealCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DealCountOutputType
   */
  select?: Prisma.DealCountOutputTypeSelect<ExtArgs> | null
}

/**
 * DealCountOutputType without action
 */
export type DealCountOutputTypeCountWishlist_deal_notificationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.wishlist_deal_notificationsWhereInput
}


export type DealSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  gameId?: boolean
  title?: boolean
  storeName?: boolean
  price?: boolean
  discountPercent?: boolean
  originalPrice?: boolean
  url?: boolean
  validFrom?: boolean
  validUntil?: boolean
  isFreebie?: boolean
  discoveredAt?: boolean
  updatedAt?: boolean
  externalId?: boolean
  source?: boolean
  thumb?: boolean
  rating?: boolean
  game?: boolean | Prisma.Deal$gameArgs<ExtArgs>
  wishlist_deal_notifications?: boolean | Prisma.Deal$wishlist_deal_notificationsArgs<ExtArgs>
  _count?: boolean | Prisma.DealCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["deal"]>

export type DealSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  gameId?: boolean
  title?: boolean
  storeName?: boolean
  price?: boolean
  discountPercent?: boolean
  originalPrice?: boolean
  url?: boolean
  validFrom?: boolean
  validUntil?: boolean
  isFreebie?: boolean
  discoveredAt?: boolean
  updatedAt?: boolean
  externalId?: boolean
  source?: boolean
  thumb?: boolean
  rating?: boolean
  game?: boolean | Prisma.Deal$gameArgs<ExtArgs>
}, ExtArgs["result"]["deal"]>

export type DealSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  gameId?: boolean
  title?: boolean
  storeName?: boolean
  price?: boolean
  discountPercent?: boolean
  originalPrice?: boolean
  url?: boolean
  validFrom?: boolean
  validUntil?: boolean
  isFreebie?: boolean
  discoveredAt?: boolean
  updatedAt?: boolean
  externalId?: boolean
  source?: boolean
  thumb?: boolean
  rating?: boolean
  game?: boolean | Prisma.Deal$gameArgs<ExtArgs>
}, ExtArgs["result"]["deal"]>

export type DealSelectScalar = {
  id?: boolean
  gameId?: boolean
  title?: boolean
  storeName?: boolean
  price?: boolean
  discountPercent?: boolean
  originalPrice?: boolean
  url?: boolean
  validFrom?: boolean
  validUntil?: boolean
  isFreebie?: boolean
  discoveredAt?: boolean
  updatedAt?: boolean
  externalId?: boolean
  source?: boolean
  thumb?: boolean
  rating?: boolean
}

export type DealOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "gameId" | "title" | "storeName" | "price" | "discountPercent" | "originalPrice" | "url" | "validFrom" | "validUntil" | "isFreebie" | "discoveredAt" | "updatedAt" | "externalId" | "source" | "thumb" | "rating", ExtArgs["result"]["deal"]>
export type DealInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  game?: boolean | Prisma.Deal$gameArgs<ExtArgs>
  wishlist_deal_notifications?: boolean | Prisma.Deal$wishlist_deal_notificationsArgs<ExtArgs>
  _count?: boolean | Prisma.DealCountOutputTypeDefaultArgs<ExtArgs>
}
export type DealIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  game?: boolean | Prisma.Deal$gameArgs<ExtArgs>
}
export type DealIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  game?: boolean | Prisma.Deal$gameArgs<ExtArgs>
}

export type $DealPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Deal"
  objects: {
    game: Prisma.$GamePayload<ExtArgs> | null
    wishlist_deal_notifications: Prisma.$wishlist_deal_notificationsPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    gameId: number | null
    title: string
    storeName: string
    price: number | null
    discountPercent: number | null
    originalPrice: number | null
    url: string
    validFrom: Date | null
    validUntil: Date | null
    isFreebie: boolean
    discoveredAt: Date
    updatedAt: Date
    externalId: string | null
    source: string | null
    thumb: string | null
    rating: number | null
  }, ExtArgs["result"]["deal"]>
  composites: {}
}

export type DealGetPayload<S extends boolean | null | undefined | DealDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DealPayload, S>

export type DealCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DealFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DealCountAggregateInputType | true
  }

export interface DealDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Deal'], meta: { name: 'Deal' } }
  /**
   * Find zero or one Deal that matches the filter.
   * @param {DealFindUniqueArgs} args - Arguments to find a Deal
   * @example
   * // Get one Deal
   * const deal = await prisma.deal.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DealFindUniqueArgs>(args: Prisma.SelectSubset<T, DealFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DealClient<runtime.Types.Result.GetResult<Prisma.$DealPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Deal that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DealFindUniqueOrThrowArgs} args - Arguments to find a Deal
   * @example
   * // Get one Deal
   * const deal = await prisma.deal.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DealFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DealFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DealClient<runtime.Types.Result.GetResult<Prisma.$DealPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Deal that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DealFindFirstArgs} args - Arguments to find a Deal
   * @example
   * // Get one Deal
   * const deal = await prisma.deal.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DealFindFirstArgs>(args?: Prisma.SelectSubset<T, DealFindFirstArgs<ExtArgs>>): Prisma.Prisma__DealClient<runtime.Types.Result.GetResult<Prisma.$DealPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Deal that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DealFindFirstOrThrowArgs} args - Arguments to find a Deal
   * @example
   * // Get one Deal
   * const deal = await prisma.deal.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DealFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DealFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DealClient<runtime.Types.Result.GetResult<Prisma.$DealPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Deals that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DealFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Deals
   * const deals = await prisma.deal.findMany()
   * 
   * // Get first 10 Deals
   * const deals = await prisma.deal.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const dealWithIdOnly = await prisma.deal.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DealFindManyArgs>(args?: Prisma.SelectSubset<T, DealFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DealPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Deal.
   * @param {DealCreateArgs} args - Arguments to create a Deal.
   * @example
   * // Create one Deal
   * const Deal = await prisma.deal.create({
   *   data: {
   *     // ... data to create a Deal
   *   }
   * })
   * 
   */
  create<T extends DealCreateArgs>(args: Prisma.SelectSubset<T, DealCreateArgs<ExtArgs>>): Prisma.Prisma__DealClient<runtime.Types.Result.GetResult<Prisma.$DealPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Deals.
   * @param {DealCreateManyArgs} args - Arguments to create many Deals.
   * @example
   * // Create many Deals
   * const deal = await prisma.deal.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DealCreateManyArgs>(args?: Prisma.SelectSubset<T, DealCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Deals and returns the data saved in the database.
   * @param {DealCreateManyAndReturnArgs} args - Arguments to create many Deals.
   * @example
   * // Create many Deals
   * const deal = await prisma.deal.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Deals and only return the `id`
   * const dealWithIdOnly = await prisma.deal.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DealCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DealCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DealPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Deal.
   * @param {DealDeleteArgs} args - Arguments to delete one Deal.
   * @example
   * // Delete one Deal
   * const Deal = await prisma.deal.delete({
   *   where: {
   *     // ... filter to delete one Deal
   *   }
   * })
   * 
   */
  delete<T extends DealDeleteArgs>(args: Prisma.SelectSubset<T, DealDeleteArgs<ExtArgs>>): Prisma.Prisma__DealClient<runtime.Types.Result.GetResult<Prisma.$DealPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Deal.
   * @param {DealUpdateArgs} args - Arguments to update one Deal.
   * @example
   * // Update one Deal
   * const deal = await prisma.deal.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DealUpdateArgs>(args: Prisma.SelectSubset<T, DealUpdateArgs<ExtArgs>>): Prisma.Prisma__DealClient<runtime.Types.Result.GetResult<Prisma.$DealPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Deals.
   * @param {DealDeleteManyArgs} args - Arguments to filter Deals to delete.
   * @example
   * // Delete a few Deals
   * const { count } = await prisma.deal.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DealDeleteManyArgs>(args?: Prisma.SelectSubset<T, DealDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Deals.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DealUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Deals
   * const deal = await prisma.deal.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DealUpdateManyArgs>(args: Prisma.SelectSubset<T, DealUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Deals and returns the data updated in the database.
   * @param {DealUpdateManyAndReturnArgs} args - Arguments to update many Deals.
   * @example
   * // Update many Deals
   * const deal = await prisma.deal.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Deals and only return the `id`
   * const dealWithIdOnly = await prisma.deal.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DealUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DealUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DealPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Deal.
   * @param {DealUpsertArgs} args - Arguments to update or create a Deal.
   * @example
   * // Update or create a Deal
   * const deal = await prisma.deal.upsert({
   *   create: {
   *     // ... data to create a Deal
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Deal we want to update
   *   }
   * })
   */
  upsert<T extends DealUpsertArgs>(args: Prisma.SelectSubset<T, DealUpsertArgs<ExtArgs>>): Prisma.Prisma__DealClient<runtime.Types.Result.GetResult<Prisma.$DealPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Deals.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DealCountArgs} args - Arguments to filter Deals to count.
   * @example
   * // Count the number of Deals
   * const count = await prisma.deal.count({
   *   where: {
   *     // ... the filter for the Deals we want to count
   *   }
   * })
  **/
  count<T extends DealCountArgs>(
    args?: Prisma.Subset<T, DealCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DealCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Deal.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DealAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DealAggregateArgs>(args: Prisma.Subset<T, DealAggregateArgs>): Prisma.PrismaPromise<GetDealAggregateType<T>>

  /**
   * Group by Deal.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DealGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DealGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DealGroupByArgs['orderBy'] }
      : { orderBy?: DealGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DealGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDealGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Deal model
 */
readonly fields: DealFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Deal.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DealClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  game<T extends Prisma.Deal$gameArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Deal$gameArgs<ExtArgs>>): Prisma.Prisma__GameClient<runtime.Types.Result.GetResult<Prisma.$GamePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  wishlist_deal_notifications<T extends Prisma.Deal$wishlist_deal_notificationsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Deal$wishlist_deal_notificationsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$wishlist_deal_notificationsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Deal model
 */
export interface DealFieldRefs {
  readonly id: Prisma.FieldRef<"Deal", 'Int'>
  readonly gameId: Prisma.FieldRef<"Deal", 'Int'>
  readonly title: Prisma.FieldRef<"Deal", 'String'>
  readonly storeName: Prisma.FieldRef<"Deal", 'String'>
  readonly price: Prisma.FieldRef<"Deal", 'Float'>
  readonly discountPercent: Prisma.FieldRef<"Deal", 'Float'>
  readonly originalPrice: Prisma.FieldRef<"Deal", 'Float'>
  readonly url: Prisma.FieldRef<"Deal", 'String'>
  readonly validFrom: Prisma.FieldRef<"Deal", 'DateTime'>
  readonly validUntil: Prisma.FieldRef<"Deal", 'DateTime'>
  readonly isFreebie: Prisma.FieldRef<"Deal", 'Boolean'>
  readonly discoveredAt: Prisma.FieldRef<"Deal", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Deal", 'DateTime'>
  readonly externalId: Prisma.FieldRef<"Deal", 'String'>
  readonly source: Prisma.FieldRef<"Deal", 'String'>
  readonly thumb: Prisma.FieldRef<"Deal", 'String'>
  readonly rating: Prisma.FieldRef<"Deal", 'Float'>
}
    

// Custom InputTypes
/**
 * Deal findUnique
 */
export type DealFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Deal
   */
  select?: Prisma.DealSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Deal
   */
  omit?: Prisma.DealOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DealInclude<ExtArgs> | null
  /**
   * Filter, which Deal to fetch.
   */
  where: Prisma.DealWhereUniqueInput
}

/**
 * Deal findUniqueOrThrow
 */
export type DealFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Deal
   */
  select?: Prisma.DealSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Deal
   */
  omit?: Prisma.DealOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DealInclude<ExtArgs> | null
  /**
   * Filter, which Deal to fetch.
   */
  where: Prisma.DealWhereUniqueInput
}

/**
 * Deal findFirst
 */
export type DealFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Deal
   */
  select?: Prisma.DealSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Deal
   */
  omit?: Prisma.DealOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DealInclude<ExtArgs> | null
  /**
   * Filter, which Deal to fetch.
   */
  where?: Prisma.DealWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Deals to fetch.
   */
  orderBy?: Prisma.DealOrderByWithRelationInput | Prisma.DealOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Deals.
   */
  cursor?: Prisma.DealWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Deals from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Deals.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Deals.
   */
  distinct?: Prisma.DealScalarFieldEnum | Prisma.DealScalarFieldEnum[]
}

/**
 * Deal findFirstOrThrow
 */
export type DealFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Deal
   */
  select?: Prisma.DealSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Deal
   */
  omit?: Prisma.DealOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DealInclude<ExtArgs> | null
  /**
   * Filter, which Deal to fetch.
   */
  where?: Prisma.DealWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Deals to fetch.
   */
  orderBy?: Prisma.DealOrderByWithRelationInput | Prisma.DealOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Deals.
   */
  cursor?: Prisma.DealWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Deals from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Deals.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Deals.
   */
  distinct?: Prisma.DealScalarFieldEnum | Prisma.DealScalarFieldEnum[]
}

/**
 * Deal findMany
 */
export type DealFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Deal
   */
  select?: Prisma.DealSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Deal
   */
  omit?: Prisma.DealOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DealInclude<ExtArgs> | null
  /**
   * Filter, which Deals to fetch.
   */
  where?: Prisma.DealWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Deals to fetch.
   */
  orderBy?: Prisma.DealOrderByWithRelationInput | Prisma.DealOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Deals.
   */
  cursor?: Prisma.DealWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Deals from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Deals.
   */
  skip?: number
  distinct?: Prisma.DealScalarFieldEnum | Prisma.DealScalarFieldEnum[]
}

/**
 * Deal create
 */
export type DealCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Deal
   */
  select?: Prisma.DealSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Deal
   */
  omit?: Prisma.DealOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DealInclude<ExtArgs> | null
  /**
   * The data needed to create a Deal.
   */
  data: Prisma.XOR<Prisma.DealCreateInput, Prisma.DealUncheckedCreateInput>
}

/**
 * Deal createMany
 */
export type DealCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Deals.
   */
  data: Prisma.DealCreateManyInput | Prisma.DealCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Deal createManyAndReturn
 */
export type DealCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Deal
   */
  select?: Prisma.DealSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Deal
   */
  omit?: Prisma.DealOmit<ExtArgs> | null
  /**
   * The data used to create many Deals.
   */
  data: Prisma.DealCreateManyInput | Prisma.DealCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DealIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Deal update
 */
export type DealUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Deal
   */
  select?: Prisma.DealSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Deal
   */
  omit?: Prisma.DealOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DealInclude<ExtArgs> | null
  /**
   * The data needed to update a Deal.
   */
  data: Prisma.XOR<Prisma.DealUpdateInput, Prisma.DealUncheckedUpdateInput>
  /**
   * Choose, which Deal to update.
   */
  where: Prisma.DealWhereUniqueInput
}

/**
 * Deal updateMany
 */
export type DealUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Deals.
   */
  data: Prisma.XOR<Prisma.DealUpdateManyMutationInput, Prisma.DealUncheckedUpdateManyInput>
  /**
   * Filter which Deals to update
   */
  where?: Prisma.DealWhereInput
  /**
   * Limit how many Deals to update.
   */
  limit?: number
}

/**
 * Deal updateManyAndReturn
 */
export type DealUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Deal
   */
  select?: Prisma.DealSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Deal
   */
  omit?: Prisma.DealOmit<ExtArgs> | null
  /**
   * The data used to update Deals.
   */
  data: Prisma.XOR<Prisma.DealUpdateManyMutationInput, Prisma.DealUncheckedUpdateManyInput>
  /**
   * Filter which Deals to update
   */
  where?: Prisma.DealWhereInput
  /**
   * Limit how many Deals to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DealIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Deal upsert
 */
export type DealUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Deal
   */
  select?: Prisma.DealSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Deal
   */
  omit?: Prisma.DealOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DealInclude<ExtArgs> | null
  /**
   * The filter to search for the Deal to update in case it exists.
   */
  where: Prisma.DealWhereUniqueInput
  /**
   * In case the Deal found by the `where` argument doesn't exist, create a new Deal with this data.
   */
  create: Prisma.XOR<Prisma.DealCreateInput, Prisma.DealUncheckedCreateInput>
  /**
   * In case the Deal was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DealUpdateInput, Prisma.DealUncheckedUpdateInput>
}

/**
 * Deal delete
 */
export type DealDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Deal
   */
  select?: Prisma.DealSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Deal
   */
  omit?: Prisma.DealOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DealInclude<ExtArgs> | null
  /**
   * Filter which Deal to delete.
   */
  where: Prisma.DealWhereUniqueInput
}

/**
 * Deal deleteMany
 */
export type DealDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Deals to delete
   */
  where?: Prisma.DealWhereInput
  /**
   * Limit how many Deals to delete.
   */
  limit?: number
}

/**
 * Deal.game
 */
export type Deal$gameArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Game
   */
  select?: Prisma.GameSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Game
   */
  omit?: Prisma.GameOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GameInclude<ExtArgs> | null
  where?: Prisma.GameWhereInput
}

/**
 * Deal.wishlist_deal_notifications
 */
export type Deal$wishlist_deal_notificationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_deal_notifications
   */
  select?: Prisma.wishlist_deal_notificationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_deal_notifications
   */
  omit?: Prisma.wishlist_deal_notificationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_deal_notificationsInclude<ExtArgs> | null
  where?: Prisma.wishlist_deal_notificationsWhereInput
  orderBy?: Prisma.wishlist_deal_notificationsOrderByWithRelationInput | Prisma.wishlist_deal_notificationsOrderByWithRelationInput[]
  cursor?: Prisma.wishlist_deal_notificationsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Wishlist_deal_notificationsScalarFieldEnum | Prisma.Wishlist_deal_notificationsScalarFieldEnum[]
}

/**
 * Deal without action
 */
export type DealDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Deal
   */
  select?: Prisma.DealSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Deal
   */
  omit?: Prisma.DealOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DealInclude<ExtArgs> | null
}
