
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
 * This file exports the `Platform` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Platform
 * 
 */
export type PlatformModel = runtime.Types.Result.DefaultSelection<Prisma.$PlatformPayload>

export type AggregatePlatform = {
  _count: PlatformCountAggregateOutputType | null
  _avg: PlatformAvgAggregateOutputType | null
  _sum: PlatformSumAggregateOutputType | null
  _min: PlatformMinAggregateOutputType | null
  _max: PlatformMaxAggregateOutputType | null
}

export type PlatformAvgAggregateOutputType = {
  id: number | null
}

export type PlatformSumAggregateOutputType = {
  id: number | null
}

export type PlatformMinAggregateOutputType = {
  id: number | null
  name: string | null
  slug: string | null
  iconUrl: string | null
  siteUrl: string | null
}

export type PlatformMaxAggregateOutputType = {
  id: number | null
  name: string | null
  slug: string | null
  iconUrl: string | null
  siteUrl: string | null
}

export type PlatformCountAggregateOutputType = {
  id: number
  name: number
  slug: number
  iconUrl: number
  siteUrl: number
  _all: number
}


export type PlatformAvgAggregateInputType = {
  id?: true
}

export type PlatformSumAggregateInputType = {
  id?: true
}

export type PlatformMinAggregateInputType = {
  id?: true
  name?: true
  slug?: true
  iconUrl?: true
  siteUrl?: true
}

export type PlatformMaxAggregateInputType = {
  id?: true
  name?: true
  slug?: true
  iconUrl?: true
  siteUrl?: true
}

export type PlatformCountAggregateInputType = {
  id?: true
  name?: true
  slug?: true
  iconUrl?: true
  siteUrl?: true
  _all?: true
}

export type PlatformAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Platform to aggregate.
   */
  where?: Prisma.PlatformWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Platforms to fetch.
   */
  orderBy?: Prisma.PlatformOrderByWithRelationInput | Prisma.PlatformOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PlatformWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Platforms from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Platforms.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Platforms
  **/
  _count?: true | PlatformCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PlatformAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PlatformSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PlatformMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PlatformMaxAggregateInputType
}

export type GetPlatformAggregateType<T extends PlatformAggregateArgs> = {
      [P in keyof T & keyof AggregatePlatform]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePlatform[P]>
    : Prisma.GetScalarType<T[P], AggregatePlatform[P]>
}




export type PlatformGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PlatformWhereInput
  orderBy?: Prisma.PlatformOrderByWithAggregationInput | Prisma.PlatformOrderByWithAggregationInput[]
  by: Prisma.PlatformScalarFieldEnum[] | Prisma.PlatformScalarFieldEnum
  having?: Prisma.PlatformScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PlatformCountAggregateInputType | true
  _avg?: PlatformAvgAggregateInputType
  _sum?: PlatformSumAggregateInputType
  _min?: PlatformMinAggregateInputType
  _max?: PlatformMaxAggregateInputType
}

export type PlatformGroupByOutputType = {
  id: number
  name: string
  slug: string
  iconUrl: string | null
  siteUrl: string | null
  _count: PlatformCountAggregateOutputType | null
  _avg: PlatformAvgAggregateOutputType | null
  _sum: PlatformSumAggregateOutputType | null
  _min: PlatformMinAggregateOutputType | null
  _max: PlatformMaxAggregateOutputType | null
}

type GetPlatformGroupByPayload<T extends PlatformGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PlatformGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PlatformGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PlatformGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PlatformGroupByOutputType[P]>
      }
    >
  > 



export type PlatformWhereInput = {
  AND?: Prisma.PlatformWhereInput | Prisma.PlatformWhereInput[]
  OR?: Prisma.PlatformWhereInput[]
  NOT?: Prisma.PlatformWhereInput | Prisma.PlatformWhereInput[]
  id?: Prisma.IntFilter<"Platform"> | number
  name?: Prisma.StringFilter<"Platform"> | string
  slug?: Prisma.StringFilter<"Platform"> | string
  iconUrl?: Prisma.StringNullableFilter<"Platform"> | string | null
  siteUrl?: Prisma.StringNullableFilter<"Platform"> | string | null
}

export type PlatformOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  iconUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  siteUrl?: Prisma.SortOrderInput | Prisma.SortOrder
}

export type PlatformWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  name?: string
  slug?: string
  AND?: Prisma.PlatformWhereInput | Prisma.PlatformWhereInput[]
  OR?: Prisma.PlatformWhereInput[]
  NOT?: Prisma.PlatformWhereInput | Prisma.PlatformWhereInput[]
  iconUrl?: Prisma.StringNullableFilter<"Platform"> | string | null
  siteUrl?: Prisma.StringNullableFilter<"Platform"> | string | null
}, "id" | "name" | "slug">

export type PlatformOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  iconUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  siteUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.PlatformCountOrderByAggregateInput
  _avg?: Prisma.PlatformAvgOrderByAggregateInput
  _max?: Prisma.PlatformMaxOrderByAggregateInput
  _min?: Prisma.PlatformMinOrderByAggregateInput
  _sum?: Prisma.PlatformSumOrderByAggregateInput
}

export type PlatformScalarWhereWithAggregatesInput = {
  AND?: Prisma.PlatformScalarWhereWithAggregatesInput | Prisma.PlatformScalarWhereWithAggregatesInput[]
  OR?: Prisma.PlatformScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PlatformScalarWhereWithAggregatesInput | Prisma.PlatformScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Platform"> | number
  name?: Prisma.StringWithAggregatesFilter<"Platform"> | string
  slug?: Prisma.StringWithAggregatesFilter<"Platform"> | string
  iconUrl?: Prisma.StringNullableWithAggregatesFilter<"Platform"> | string | null
  siteUrl?: Prisma.StringNullableWithAggregatesFilter<"Platform"> | string | null
}

export type PlatformCreateInput = {
  name: string
  slug: string
  iconUrl?: string | null
  siteUrl?: string | null
}

export type PlatformUncheckedCreateInput = {
  id?: number
  name: string
  slug: string
  iconUrl?: string | null
  siteUrl?: string | null
}

export type PlatformUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  iconUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  siteUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type PlatformUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  iconUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  siteUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type PlatformCreateManyInput = {
  id?: number
  name: string
  slug: string
  iconUrl?: string | null
  siteUrl?: string | null
}

export type PlatformUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  iconUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  siteUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type PlatformUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  iconUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  siteUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type PlatformCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  iconUrl?: Prisma.SortOrder
  siteUrl?: Prisma.SortOrder
}

export type PlatformAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type PlatformMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  iconUrl?: Prisma.SortOrder
  siteUrl?: Prisma.SortOrder
}

export type PlatformMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  iconUrl?: Prisma.SortOrder
  siteUrl?: Prisma.SortOrder
}

export type PlatformSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}



export type PlatformSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  slug?: boolean
  iconUrl?: boolean
  siteUrl?: boolean
}, ExtArgs["result"]["platform"]>

export type PlatformSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  slug?: boolean
  iconUrl?: boolean
  siteUrl?: boolean
}, ExtArgs["result"]["platform"]>

export type PlatformSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  slug?: boolean
  iconUrl?: boolean
  siteUrl?: boolean
}, ExtArgs["result"]["platform"]>

export type PlatformSelectScalar = {
  id?: boolean
  name?: boolean
  slug?: boolean
  iconUrl?: boolean
  siteUrl?: boolean
}

export type PlatformOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "slug" | "iconUrl" | "siteUrl", ExtArgs["result"]["platform"]>

export type $PlatformPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Platform"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string
    slug: string
    iconUrl: string | null
    siteUrl: string | null
  }, ExtArgs["result"]["platform"]>
  composites: {}
}

export type PlatformGetPayload<S extends boolean | null | undefined | PlatformDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PlatformPayload, S>

export type PlatformCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PlatformFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PlatformCountAggregateInputType | true
  }

export interface PlatformDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Platform'], meta: { name: 'Platform' } }
  /**
   * Find zero or one Platform that matches the filter.
   * @param {PlatformFindUniqueArgs} args - Arguments to find a Platform
   * @example
   * // Get one Platform
   * const platform = await prisma.platform.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PlatformFindUniqueArgs>(args: Prisma.SelectSubset<T, PlatformFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PlatformClient<runtime.Types.Result.GetResult<Prisma.$PlatformPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Platform that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PlatformFindUniqueOrThrowArgs} args - Arguments to find a Platform
   * @example
   * // Get one Platform
   * const platform = await prisma.platform.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PlatformFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PlatformFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PlatformClient<runtime.Types.Result.GetResult<Prisma.$PlatformPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Platform that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlatformFindFirstArgs} args - Arguments to find a Platform
   * @example
   * // Get one Platform
   * const platform = await prisma.platform.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PlatformFindFirstArgs>(args?: Prisma.SelectSubset<T, PlatformFindFirstArgs<ExtArgs>>): Prisma.Prisma__PlatformClient<runtime.Types.Result.GetResult<Prisma.$PlatformPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Platform that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlatformFindFirstOrThrowArgs} args - Arguments to find a Platform
   * @example
   * // Get one Platform
   * const platform = await prisma.platform.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PlatformFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PlatformFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PlatformClient<runtime.Types.Result.GetResult<Prisma.$PlatformPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Platforms that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlatformFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Platforms
   * const platforms = await prisma.platform.findMany()
   * 
   * // Get first 10 Platforms
   * const platforms = await prisma.platform.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const platformWithIdOnly = await prisma.platform.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PlatformFindManyArgs>(args?: Prisma.SelectSubset<T, PlatformFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlatformPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Platform.
   * @param {PlatformCreateArgs} args - Arguments to create a Platform.
   * @example
   * // Create one Platform
   * const Platform = await prisma.platform.create({
   *   data: {
   *     // ... data to create a Platform
   *   }
   * })
   * 
   */
  create<T extends PlatformCreateArgs>(args: Prisma.SelectSubset<T, PlatformCreateArgs<ExtArgs>>): Prisma.Prisma__PlatformClient<runtime.Types.Result.GetResult<Prisma.$PlatformPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Platforms.
   * @param {PlatformCreateManyArgs} args - Arguments to create many Platforms.
   * @example
   * // Create many Platforms
   * const platform = await prisma.platform.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PlatformCreateManyArgs>(args?: Prisma.SelectSubset<T, PlatformCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Platforms and returns the data saved in the database.
   * @param {PlatformCreateManyAndReturnArgs} args - Arguments to create many Platforms.
   * @example
   * // Create many Platforms
   * const platform = await prisma.platform.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Platforms and only return the `id`
   * const platformWithIdOnly = await prisma.platform.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PlatformCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PlatformCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlatformPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Platform.
   * @param {PlatformDeleteArgs} args - Arguments to delete one Platform.
   * @example
   * // Delete one Platform
   * const Platform = await prisma.platform.delete({
   *   where: {
   *     // ... filter to delete one Platform
   *   }
   * })
   * 
   */
  delete<T extends PlatformDeleteArgs>(args: Prisma.SelectSubset<T, PlatformDeleteArgs<ExtArgs>>): Prisma.Prisma__PlatformClient<runtime.Types.Result.GetResult<Prisma.$PlatformPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Platform.
   * @param {PlatformUpdateArgs} args - Arguments to update one Platform.
   * @example
   * // Update one Platform
   * const platform = await prisma.platform.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PlatformUpdateArgs>(args: Prisma.SelectSubset<T, PlatformUpdateArgs<ExtArgs>>): Prisma.Prisma__PlatformClient<runtime.Types.Result.GetResult<Prisma.$PlatformPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Platforms.
   * @param {PlatformDeleteManyArgs} args - Arguments to filter Platforms to delete.
   * @example
   * // Delete a few Platforms
   * const { count } = await prisma.platform.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PlatformDeleteManyArgs>(args?: Prisma.SelectSubset<T, PlatformDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Platforms.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlatformUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Platforms
   * const platform = await prisma.platform.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PlatformUpdateManyArgs>(args: Prisma.SelectSubset<T, PlatformUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Platforms and returns the data updated in the database.
   * @param {PlatformUpdateManyAndReturnArgs} args - Arguments to update many Platforms.
   * @example
   * // Update many Platforms
   * const platform = await prisma.platform.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Platforms and only return the `id`
   * const platformWithIdOnly = await prisma.platform.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PlatformUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PlatformUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlatformPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Platform.
   * @param {PlatformUpsertArgs} args - Arguments to update or create a Platform.
   * @example
   * // Update or create a Platform
   * const platform = await prisma.platform.upsert({
   *   create: {
   *     // ... data to create a Platform
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Platform we want to update
   *   }
   * })
   */
  upsert<T extends PlatformUpsertArgs>(args: Prisma.SelectSubset<T, PlatformUpsertArgs<ExtArgs>>): Prisma.Prisma__PlatformClient<runtime.Types.Result.GetResult<Prisma.$PlatformPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Platforms.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlatformCountArgs} args - Arguments to filter Platforms to count.
   * @example
   * // Count the number of Platforms
   * const count = await prisma.platform.count({
   *   where: {
   *     // ... the filter for the Platforms we want to count
   *   }
   * })
  **/
  count<T extends PlatformCountArgs>(
    args?: Prisma.Subset<T, PlatformCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PlatformCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Platform.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlatformAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PlatformAggregateArgs>(args: Prisma.Subset<T, PlatformAggregateArgs>): Prisma.PrismaPromise<GetPlatformAggregateType<T>>

  /**
   * Group by Platform.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlatformGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PlatformGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PlatformGroupByArgs['orderBy'] }
      : { orderBy?: PlatformGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PlatformGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPlatformGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Platform model
 */
readonly fields: PlatformFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Platform.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PlatformClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Platform model
 */
export interface PlatformFieldRefs {
  readonly id: Prisma.FieldRef<"Platform", 'Int'>
  readonly name: Prisma.FieldRef<"Platform", 'String'>
  readonly slug: Prisma.FieldRef<"Platform", 'String'>
  readonly iconUrl: Prisma.FieldRef<"Platform", 'String'>
  readonly siteUrl: Prisma.FieldRef<"Platform", 'String'>
}
    

// Custom InputTypes
/**
 * Platform findUnique
 */
export type PlatformFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Platform
   */
  select?: Prisma.PlatformSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Platform
   */
  omit?: Prisma.PlatformOmit<ExtArgs> | null
  /**
   * Filter, which Platform to fetch.
   */
  where: Prisma.PlatformWhereUniqueInput
}

/**
 * Platform findUniqueOrThrow
 */
export type PlatformFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Platform
   */
  select?: Prisma.PlatformSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Platform
   */
  omit?: Prisma.PlatformOmit<ExtArgs> | null
  /**
   * Filter, which Platform to fetch.
   */
  where: Prisma.PlatformWhereUniqueInput
}

/**
 * Platform findFirst
 */
export type PlatformFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Platform
   */
  select?: Prisma.PlatformSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Platform
   */
  omit?: Prisma.PlatformOmit<ExtArgs> | null
  /**
   * Filter, which Platform to fetch.
   */
  where?: Prisma.PlatformWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Platforms to fetch.
   */
  orderBy?: Prisma.PlatformOrderByWithRelationInput | Prisma.PlatformOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Platforms.
   */
  cursor?: Prisma.PlatformWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Platforms from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Platforms.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Platforms.
   */
  distinct?: Prisma.PlatformScalarFieldEnum | Prisma.PlatformScalarFieldEnum[]
}

/**
 * Platform findFirstOrThrow
 */
export type PlatformFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Platform
   */
  select?: Prisma.PlatformSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Platform
   */
  omit?: Prisma.PlatformOmit<ExtArgs> | null
  /**
   * Filter, which Platform to fetch.
   */
  where?: Prisma.PlatformWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Platforms to fetch.
   */
  orderBy?: Prisma.PlatformOrderByWithRelationInput | Prisma.PlatformOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Platforms.
   */
  cursor?: Prisma.PlatformWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Platforms from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Platforms.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Platforms.
   */
  distinct?: Prisma.PlatformScalarFieldEnum | Prisma.PlatformScalarFieldEnum[]
}

/**
 * Platform findMany
 */
export type PlatformFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Platform
   */
  select?: Prisma.PlatformSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Platform
   */
  omit?: Prisma.PlatformOmit<ExtArgs> | null
  /**
   * Filter, which Platforms to fetch.
   */
  where?: Prisma.PlatformWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Platforms to fetch.
   */
  orderBy?: Prisma.PlatformOrderByWithRelationInput | Prisma.PlatformOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Platforms.
   */
  cursor?: Prisma.PlatformWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Platforms from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Platforms.
   */
  skip?: number
  distinct?: Prisma.PlatformScalarFieldEnum | Prisma.PlatformScalarFieldEnum[]
}

/**
 * Platform create
 */
export type PlatformCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Platform
   */
  select?: Prisma.PlatformSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Platform
   */
  omit?: Prisma.PlatformOmit<ExtArgs> | null
  /**
   * The data needed to create a Platform.
   */
  data: Prisma.XOR<Prisma.PlatformCreateInput, Prisma.PlatformUncheckedCreateInput>
}

/**
 * Platform createMany
 */
export type PlatformCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Platforms.
   */
  data: Prisma.PlatformCreateManyInput | Prisma.PlatformCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Platform createManyAndReturn
 */
export type PlatformCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Platform
   */
  select?: Prisma.PlatformSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Platform
   */
  omit?: Prisma.PlatformOmit<ExtArgs> | null
  /**
   * The data used to create many Platforms.
   */
  data: Prisma.PlatformCreateManyInput | Prisma.PlatformCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Platform update
 */
export type PlatformUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Platform
   */
  select?: Prisma.PlatformSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Platform
   */
  omit?: Prisma.PlatformOmit<ExtArgs> | null
  /**
   * The data needed to update a Platform.
   */
  data: Prisma.XOR<Prisma.PlatformUpdateInput, Prisma.PlatformUncheckedUpdateInput>
  /**
   * Choose, which Platform to update.
   */
  where: Prisma.PlatformWhereUniqueInput
}

/**
 * Platform updateMany
 */
export type PlatformUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Platforms.
   */
  data: Prisma.XOR<Prisma.PlatformUpdateManyMutationInput, Prisma.PlatformUncheckedUpdateManyInput>
  /**
   * Filter which Platforms to update
   */
  where?: Prisma.PlatformWhereInput
  /**
   * Limit how many Platforms to update.
   */
  limit?: number
}

/**
 * Platform updateManyAndReturn
 */
export type PlatformUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Platform
   */
  select?: Prisma.PlatformSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Platform
   */
  omit?: Prisma.PlatformOmit<ExtArgs> | null
  /**
   * The data used to update Platforms.
   */
  data: Prisma.XOR<Prisma.PlatformUpdateManyMutationInput, Prisma.PlatformUncheckedUpdateManyInput>
  /**
   * Filter which Platforms to update
   */
  where?: Prisma.PlatformWhereInput
  /**
   * Limit how many Platforms to update.
   */
  limit?: number
}

/**
 * Platform upsert
 */
export type PlatformUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Platform
   */
  select?: Prisma.PlatformSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Platform
   */
  omit?: Prisma.PlatformOmit<ExtArgs> | null
  /**
   * The filter to search for the Platform to update in case it exists.
   */
  where: Prisma.PlatformWhereUniqueInput
  /**
   * In case the Platform found by the `where` argument doesn't exist, create a new Platform with this data.
   */
  create: Prisma.XOR<Prisma.PlatformCreateInput, Prisma.PlatformUncheckedCreateInput>
  /**
   * In case the Platform was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PlatformUpdateInput, Prisma.PlatformUncheckedUpdateInput>
}

/**
 * Platform delete
 */
export type PlatformDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Platform
   */
  select?: Prisma.PlatformSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Platform
   */
  omit?: Prisma.PlatformOmit<ExtArgs> | null
  /**
   * Filter which Platform to delete.
   */
  where: Prisma.PlatformWhereUniqueInput
}

/**
 * Platform deleteMany
 */
export type PlatformDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Platforms to delete
   */
  where?: Prisma.PlatformWhereInput
  /**
   * Limit how many Platforms to delete.
   */
  limit?: number
}

/**
 * Platform without action
 */
export type PlatformDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Platform
   */
  select?: Prisma.PlatformSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Platform
   */
  omit?: Prisma.PlatformOmit<ExtArgs> | null
}
