
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
 * This file exports the `wishlist_deal_notifications` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model wishlist_deal_notifications
 * 
 */
export type wishlist_deal_notificationsModel = runtime.Types.Result.DefaultSelection<Prisma.$wishlist_deal_notificationsPayload>

export type AggregateWishlist_deal_notifications = {
  _count: Wishlist_deal_notificationsCountAggregateOutputType | null
  _avg: Wishlist_deal_notificationsAvgAggregateOutputType | null
  _sum: Wishlist_deal_notificationsSumAggregateOutputType | null
  _min: Wishlist_deal_notificationsMinAggregateOutputType | null
  _max: Wishlist_deal_notificationsMaxAggregateOutputType | null
}

export type Wishlist_deal_notificationsAvgAggregateOutputType = {
  id: number | null
  userId: number | null
  gameId: number | null
  dealId: number | null
}

export type Wishlist_deal_notificationsSumAggregateOutputType = {
  id: number | null
  userId: number | null
  gameId: number | null
  dealId: number | null
}

export type Wishlist_deal_notificationsMinAggregateOutputType = {
  id: number | null
  userId: number | null
  gameId: number | null
  dealId: number | null
  notificationSent: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type Wishlist_deal_notificationsMaxAggregateOutputType = {
  id: number | null
  userId: number | null
  gameId: number | null
  dealId: number | null
  notificationSent: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type Wishlist_deal_notificationsCountAggregateOutputType = {
  id: number
  userId: number
  gameId: number
  dealId: number
  notificationSent: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type Wishlist_deal_notificationsAvgAggregateInputType = {
  id?: true
  userId?: true
  gameId?: true
  dealId?: true
}

export type Wishlist_deal_notificationsSumAggregateInputType = {
  id?: true
  userId?: true
  gameId?: true
  dealId?: true
}

export type Wishlist_deal_notificationsMinAggregateInputType = {
  id?: true
  userId?: true
  gameId?: true
  dealId?: true
  notificationSent?: true
  createdAt?: true
  updatedAt?: true
}

export type Wishlist_deal_notificationsMaxAggregateInputType = {
  id?: true
  userId?: true
  gameId?: true
  dealId?: true
  notificationSent?: true
  createdAt?: true
  updatedAt?: true
}

export type Wishlist_deal_notificationsCountAggregateInputType = {
  id?: true
  userId?: true
  gameId?: true
  dealId?: true
  notificationSent?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type Wishlist_deal_notificationsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which wishlist_deal_notifications to aggregate.
   */
  where?: Prisma.wishlist_deal_notificationsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of wishlist_deal_notifications to fetch.
   */
  orderBy?: Prisma.wishlist_deal_notificationsOrderByWithRelationInput | Prisma.wishlist_deal_notificationsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.wishlist_deal_notificationsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` wishlist_deal_notifications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` wishlist_deal_notifications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned wishlist_deal_notifications
  **/
  _count?: true | Wishlist_deal_notificationsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Wishlist_deal_notificationsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Wishlist_deal_notificationsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Wishlist_deal_notificationsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Wishlist_deal_notificationsMaxAggregateInputType
}

export type GetWishlist_deal_notificationsAggregateType<T extends Wishlist_deal_notificationsAggregateArgs> = {
      [P in keyof T & keyof AggregateWishlist_deal_notifications]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateWishlist_deal_notifications[P]>
    : Prisma.GetScalarType<T[P], AggregateWishlist_deal_notifications[P]>
}




export type wishlist_deal_notificationsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.wishlist_deal_notificationsWhereInput
  orderBy?: Prisma.wishlist_deal_notificationsOrderByWithAggregationInput | Prisma.wishlist_deal_notificationsOrderByWithAggregationInput[]
  by: Prisma.Wishlist_deal_notificationsScalarFieldEnum[] | Prisma.Wishlist_deal_notificationsScalarFieldEnum
  having?: Prisma.wishlist_deal_notificationsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Wishlist_deal_notificationsCountAggregateInputType | true
  _avg?: Wishlist_deal_notificationsAvgAggregateInputType
  _sum?: Wishlist_deal_notificationsSumAggregateInputType
  _min?: Wishlist_deal_notificationsMinAggregateInputType
  _max?: Wishlist_deal_notificationsMaxAggregateInputType
}

export type Wishlist_deal_notificationsGroupByOutputType = {
  id: number
  userId: number
  gameId: number
  dealId: number
  notificationSent: boolean
  createdAt: Date
  updatedAt: Date
  _count: Wishlist_deal_notificationsCountAggregateOutputType | null
  _avg: Wishlist_deal_notificationsAvgAggregateOutputType | null
  _sum: Wishlist_deal_notificationsSumAggregateOutputType | null
  _min: Wishlist_deal_notificationsMinAggregateOutputType | null
  _max: Wishlist_deal_notificationsMaxAggregateOutputType | null
}

type GetWishlist_deal_notificationsGroupByPayload<T extends wishlist_deal_notificationsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Wishlist_deal_notificationsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Wishlist_deal_notificationsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Wishlist_deal_notificationsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Wishlist_deal_notificationsGroupByOutputType[P]>
      }
    >
  > 



export type wishlist_deal_notificationsWhereInput = {
  AND?: Prisma.wishlist_deal_notificationsWhereInput | Prisma.wishlist_deal_notificationsWhereInput[]
  OR?: Prisma.wishlist_deal_notificationsWhereInput[]
  NOT?: Prisma.wishlist_deal_notificationsWhereInput | Prisma.wishlist_deal_notificationsWhereInput[]
  id?: Prisma.IntFilter<"wishlist_deal_notifications"> | number
  userId?: Prisma.IntFilter<"wishlist_deal_notifications"> | number
  gameId?: Prisma.IntFilter<"wishlist_deal_notifications"> | number
  dealId?: Prisma.IntFilter<"wishlist_deal_notifications"> | number
  notificationSent?: Prisma.BoolFilter<"wishlist_deal_notifications"> | boolean
  createdAt?: Prisma.DateTimeFilter<"wishlist_deal_notifications"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"wishlist_deal_notifications"> | Date | string
  deals?: Prisma.XOR<Prisma.DealScalarRelationFilter, Prisma.DealWhereInput>
  games?: Prisma.XOR<Prisma.GameScalarRelationFilter, Prisma.GameWhereInput>
  users?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type wishlist_deal_notificationsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  gameId?: Prisma.SortOrder
  dealId?: Prisma.SortOrder
  notificationSent?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deals?: Prisma.DealOrderByWithRelationInput
  games?: Prisma.GameOrderByWithRelationInput
  users?: Prisma.UserOrderByWithRelationInput
}

export type wishlist_deal_notificationsWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  userId_dealId?: Prisma.wishlist_deal_notificationsUserIdDealIdCompoundUniqueInput
  AND?: Prisma.wishlist_deal_notificationsWhereInput | Prisma.wishlist_deal_notificationsWhereInput[]
  OR?: Prisma.wishlist_deal_notificationsWhereInput[]
  NOT?: Prisma.wishlist_deal_notificationsWhereInput | Prisma.wishlist_deal_notificationsWhereInput[]
  userId?: Prisma.IntFilter<"wishlist_deal_notifications"> | number
  gameId?: Prisma.IntFilter<"wishlist_deal_notifications"> | number
  dealId?: Prisma.IntFilter<"wishlist_deal_notifications"> | number
  notificationSent?: Prisma.BoolFilter<"wishlist_deal_notifications"> | boolean
  createdAt?: Prisma.DateTimeFilter<"wishlist_deal_notifications"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"wishlist_deal_notifications"> | Date | string
  deals?: Prisma.XOR<Prisma.DealScalarRelationFilter, Prisma.DealWhereInput>
  games?: Prisma.XOR<Prisma.GameScalarRelationFilter, Prisma.GameWhereInput>
  users?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id" | "userId_dealId">

export type wishlist_deal_notificationsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  gameId?: Prisma.SortOrder
  dealId?: Prisma.SortOrder
  notificationSent?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.wishlist_deal_notificationsCountOrderByAggregateInput
  _avg?: Prisma.wishlist_deal_notificationsAvgOrderByAggregateInput
  _max?: Prisma.wishlist_deal_notificationsMaxOrderByAggregateInput
  _min?: Prisma.wishlist_deal_notificationsMinOrderByAggregateInput
  _sum?: Prisma.wishlist_deal_notificationsSumOrderByAggregateInput
}

export type wishlist_deal_notificationsScalarWhereWithAggregatesInput = {
  AND?: Prisma.wishlist_deal_notificationsScalarWhereWithAggregatesInput | Prisma.wishlist_deal_notificationsScalarWhereWithAggregatesInput[]
  OR?: Prisma.wishlist_deal_notificationsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.wishlist_deal_notificationsScalarWhereWithAggregatesInput | Prisma.wishlist_deal_notificationsScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"wishlist_deal_notifications"> | number
  userId?: Prisma.IntWithAggregatesFilter<"wishlist_deal_notifications"> | number
  gameId?: Prisma.IntWithAggregatesFilter<"wishlist_deal_notifications"> | number
  dealId?: Prisma.IntWithAggregatesFilter<"wishlist_deal_notifications"> | number
  notificationSent?: Prisma.BoolWithAggregatesFilter<"wishlist_deal_notifications"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"wishlist_deal_notifications"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"wishlist_deal_notifications"> | Date | string
}

export type wishlist_deal_notificationsCreateInput = {
  notificationSent?: boolean
  createdAt?: Date | string
  updatedAt: Date | string
  deals: Prisma.DealCreateNestedOneWithoutWishlist_deal_notificationsInput
  games: Prisma.GameCreateNestedOneWithoutWishlist_deal_notificationsInput
  users: Prisma.UserCreateNestedOneWithoutWishlist_deal_notificationsInput
}

export type wishlist_deal_notificationsUncheckedCreateInput = {
  id?: number
  userId: number
  gameId: number
  dealId: number
  notificationSent?: boolean
  createdAt?: Date | string
  updatedAt: Date | string
}

export type wishlist_deal_notificationsUpdateInput = {
  notificationSent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deals?: Prisma.DealUpdateOneRequiredWithoutWishlist_deal_notificationsNestedInput
  games?: Prisma.GameUpdateOneRequiredWithoutWishlist_deal_notificationsNestedInput
  users?: Prisma.UserUpdateOneRequiredWithoutWishlist_deal_notificationsNestedInput
}

export type wishlist_deal_notificationsUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  gameId?: Prisma.IntFieldUpdateOperationsInput | number
  dealId?: Prisma.IntFieldUpdateOperationsInput | number
  notificationSent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type wishlist_deal_notificationsCreateManyInput = {
  id?: number
  userId: number
  gameId: number
  dealId: number
  notificationSent?: boolean
  createdAt?: Date | string
  updatedAt: Date | string
}

export type wishlist_deal_notificationsUpdateManyMutationInput = {
  notificationSent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type wishlist_deal_notificationsUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  gameId?: Prisma.IntFieldUpdateOperationsInput | number
  dealId?: Prisma.IntFieldUpdateOperationsInput | number
  notificationSent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type Wishlist_deal_notificationsListRelationFilter = {
  every?: Prisma.wishlist_deal_notificationsWhereInput
  some?: Prisma.wishlist_deal_notificationsWhereInput
  none?: Prisma.wishlist_deal_notificationsWhereInput
}

export type wishlist_deal_notificationsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type wishlist_deal_notificationsUserIdDealIdCompoundUniqueInput = {
  userId: number
  dealId: number
}

export type wishlist_deal_notificationsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  gameId?: Prisma.SortOrder
  dealId?: Prisma.SortOrder
  notificationSent?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type wishlist_deal_notificationsAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  gameId?: Prisma.SortOrder
  dealId?: Prisma.SortOrder
}

export type wishlist_deal_notificationsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  gameId?: Prisma.SortOrder
  dealId?: Prisma.SortOrder
  notificationSent?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type wishlist_deal_notificationsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  gameId?: Prisma.SortOrder
  dealId?: Prisma.SortOrder
  notificationSent?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type wishlist_deal_notificationsSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  gameId?: Prisma.SortOrder
  dealId?: Prisma.SortOrder
}

export type wishlist_deal_notificationsCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.wishlist_deal_notificationsCreateWithoutUsersInput, Prisma.wishlist_deal_notificationsUncheckedCreateWithoutUsersInput> | Prisma.wishlist_deal_notificationsCreateWithoutUsersInput[] | Prisma.wishlist_deal_notificationsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.wishlist_deal_notificationsCreateOrConnectWithoutUsersInput | Prisma.wishlist_deal_notificationsCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.wishlist_deal_notificationsCreateManyUsersInputEnvelope
  connect?: Prisma.wishlist_deal_notificationsWhereUniqueInput | Prisma.wishlist_deal_notificationsWhereUniqueInput[]
}

export type wishlist_deal_notificationsUncheckedCreateNestedManyWithoutUsersInput = {
  create?: Prisma.XOR<Prisma.wishlist_deal_notificationsCreateWithoutUsersInput, Prisma.wishlist_deal_notificationsUncheckedCreateWithoutUsersInput> | Prisma.wishlist_deal_notificationsCreateWithoutUsersInput[] | Prisma.wishlist_deal_notificationsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.wishlist_deal_notificationsCreateOrConnectWithoutUsersInput | Prisma.wishlist_deal_notificationsCreateOrConnectWithoutUsersInput[]
  createMany?: Prisma.wishlist_deal_notificationsCreateManyUsersInputEnvelope
  connect?: Prisma.wishlist_deal_notificationsWhereUniqueInput | Prisma.wishlist_deal_notificationsWhereUniqueInput[]
}

export type wishlist_deal_notificationsUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.wishlist_deal_notificationsCreateWithoutUsersInput, Prisma.wishlist_deal_notificationsUncheckedCreateWithoutUsersInput> | Prisma.wishlist_deal_notificationsCreateWithoutUsersInput[] | Prisma.wishlist_deal_notificationsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.wishlist_deal_notificationsCreateOrConnectWithoutUsersInput | Prisma.wishlist_deal_notificationsCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.wishlist_deal_notificationsUpsertWithWhereUniqueWithoutUsersInput | Prisma.wishlist_deal_notificationsUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.wishlist_deal_notificationsCreateManyUsersInputEnvelope
  set?: Prisma.wishlist_deal_notificationsWhereUniqueInput | Prisma.wishlist_deal_notificationsWhereUniqueInput[]
  disconnect?: Prisma.wishlist_deal_notificationsWhereUniqueInput | Prisma.wishlist_deal_notificationsWhereUniqueInput[]
  delete?: Prisma.wishlist_deal_notificationsWhereUniqueInput | Prisma.wishlist_deal_notificationsWhereUniqueInput[]
  connect?: Prisma.wishlist_deal_notificationsWhereUniqueInput | Prisma.wishlist_deal_notificationsWhereUniqueInput[]
  update?: Prisma.wishlist_deal_notificationsUpdateWithWhereUniqueWithoutUsersInput | Prisma.wishlist_deal_notificationsUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.wishlist_deal_notificationsUpdateManyWithWhereWithoutUsersInput | Prisma.wishlist_deal_notificationsUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.wishlist_deal_notificationsScalarWhereInput | Prisma.wishlist_deal_notificationsScalarWhereInput[]
}

export type wishlist_deal_notificationsUncheckedUpdateManyWithoutUsersNestedInput = {
  create?: Prisma.XOR<Prisma.wishlist_deal_notificationsCreateWithoutUsersInput, Prisma.wishlist_deal_notificationsUncheckedCreateWithoutUsersInput> | Prisma.wishlist_deal_notificationsCreateWithoutUsersInput[] | Prisma.wishlist_deal_notificationsUncheckedCreateWithoutUsersInput[]
  connectOrCreate?: Prisma.wishlist_deal_notificationsCreateOrConnectWithoutUsersInput | Prisma.wishlist_deal_notificationsCreateOrConnectWithoutUsersInput[]
  upsert?: Prisma.wishlist_deal_notificationsUpsertWithWhereUniqueWithoutUsersInput | Prisma.wishlist_deal_notificationsUpsertWithWhereUniqueWithoutUsersInput[]
  createMany?: Prisma.wishlist_deal_notificationsCreateManyUsersInputEnvelope
  set?: Prisma.wishlist_deal_notificationsWhereUniqueInput | Prisma.wishlist_deal_notificationsWhereUniqueInput[]
  disconnect?: Prisma.wishlist_deal_notificationsWhereUniqueInput | Prisma.wishlist_deal_notificationsWhereUniqueInput[]
  delete?: Prisma.wishlist_deal_notificationsWhereUniqueInput | Prisma.wishlist_deal_notificationsWhereUniqueInput[]
  connect?: Prisma.wishlist_deal_notificationsWhereUniqueInput | Prisma.wishlist_deal_notificationsWhereUniqueInput[]
  update?: Prisma.wishlist_deal_notificationsUpdateWithWhereUniqueWithoutUsersInput | Prisma.wishlist_deal_notificationsUpdateWithWhereUniqueWithoutUsersInput[]
  updateMany?: Prisma.wishlist_deal_notificationsUpdateManyWithWhereWithoutUsersInput | Prisma.wishlist_deal_notificationsUpdateManyWithWhereWithoutUsersInput[]
  deleteMany?: Prisma.wishlist_deal_notificationsScalarWhereInput | Prisma.wishlist_deal_notificationsScalarWhereInput[]
}

export type wishlist_deal_notificationsCreateNestedManyWithoutGamesInput = {
  create?: Prisma.XOR<Prisma.wishlist_deal_notificationsCreateWithoutGamesInput, Prisma.wishlist_deal_notificationsUncheckedCreateWithoutGamesInput> | Prisma.wishlist_deal_notificationsCreateWithoutGamesInput[] | Prisma.wishlist_deal_notificationsUncheckedCreateWithoutGamesInput[]
  connectOrCreate?: Prisma.wishlist_deal_notificationsCreateOrConnectWithoutGamesInput | Prisma.wishlist_deal_notificationsCreateOrConnectWithoutGamesInput[]
  createMany?: Prisma.wishlist_deal_notificationsCreateManyGamesInputEnvelope
  connect?: Prisma.wishlist_deal_notificationsWhereUniqueInput | Prisma.wishlist_deal_notificationsWhereUniqueInput[]
}

export type wishlist_deal_notificationsUncheckedCreateNestedManyWithoutGamesInput = {
  create?: Prisma.XOR<Prisma.wishlist_deal_notificationsCreateWithoutGamesInput, Prisma.wishlist_deal_notificationsUncheckedCreateWithoutGamesInput> | Prisma.wishlist_deal_notificationsCreateWithoutGamesInput[] | Prisma.wishlist_deal_notificationsUncheckedCreateWithoutGamesInput[]
  connectOrCreate?: Prisma.wishlist_deal_notificationsCreateOrConnectWithoutGamesInput | Prisma.wishlist_deal_notificationsCreateOrConnectWithoutGamesInput[]
  createMany?: Prisma.wishlist_deal_notificationsCreateManyGamesInputEnvelope
  connect?: Prisma.wishlist_deal_notificationsWhereUniqueInput | Prisma.wishlist_deal_notificationsWhereUniqueInput[]
}

export type wishlist_deal_notificationsUpdateManyWithoutGamesNestedInput = {
  create?: Prisma.XOR<Prisma.wishlist_deal_notificationsCreateWithoutGamesInput, Prisma.wishlist_deal_notificationsUncheckedCreateWithoutGamesInput> | Prisma.wishlist_deal_notificationsCreateWithoutGamesInput[] | Prisma.wishlist_deal_notificationsUncheckedCreateWithoutGamesInput[]
  connectOrCreate?: Prisma.wishlist_deal_notificationsCreateOrConnectWithoutGamesInput | Prisma.wishlist_deal_notificationsCreateOrConnectWithoutGamesInput[]
  upsert?: Prisma.wishlist_deal_notificationsUpsertWithWhereUniqueWithoutGamesInput | Prisma.wishlist_deal_notificationsUpsertWithWhereUniqueWithoutGamesInput[]
  createMany?: Prisma.wishlist_deal_notificationsCreateManyGamesInputEnvelope
  set?: Prisma.wishlist_deal_notificationsWhereUniqueInput | Prisma.wishlist_deal_notificationsWhereUniqueInput[]
  disconnect?: Prisma.wishlist_deal_notificationsWhereUniqueInput | Prisma.wishlist_deal_notificationsWhereUniqueInput[]
  delete?: Prisma.wishlist_deal_notificationsWhereUniqueInput | Prisma.wishlist_deal_notificationsWhereUniqueInput[]
  connect?: Prisma.wishlist_deal_notificationsWhereUniqueInput | Prisma.wishlist_deal_notificationsWhereUniqueInput[]
  update?: Prisma.wishlist_deal_notificationsUpdateWithWhereUniqueWithoutGamesInput | Prisma.wishlist_deal_notificationsUpdateWithWhereUniqueWithoutGamesInput[]
  updateMany?: Prisma.wishlist_deal_notificationsUpdateManyWithWhereWithoutGamesInput | Prisma.wishlist_deal_notificationsUpdateManyWithWhereWithoutGamesInput[]
  deleteMany?: Prisma.wishlist_deal_notificationsScalarWhereInput | Prisma.wishlist_deal_notificationsScalarWhereInput[]
}

export type wishlist_deal_notificationsUncheckedUpdateManyWithoutGamesNestedInput = {
  create?: Prisma.XOR<Prisma.wishlist_deal_notificationsCreateWithoutGamesInput, Prisma.wishlist_deal_notificationsUncheckedCreateWithoutGamesInput> | Prisma.wishlist_deal_notificationsCreateWithoutGamesInput[] | Prisma.wishlist_deal_notificationsUncheckedCreateWithoutGamesInput[]
  connectOrCreate?: Prisma.wishlist_deal_notificationsCreateOrConnectWithoutGamesInput | Prisma.wishlist_deal_notificationsCreateOrConnectWithoutGamesInput[]
  upsert?: Prisma.wishlist_deal_notificationsUpsertWithWhereUniqueWithoutGamesInput | Prisma.wishlist_deal_notificationsUpsertWithWhereUniqueWithoutGamesInput[]
  createMany?: Prisma.wishlist_deal_notificationsCreateManyGamesInputEnvelope
  set?: Prisma.wishlist_deal_notificationsWhereUniqueInput | Prisma.wishlist_deal_notificationsWhereUniqueInput[]
  disconnect?: Prisma.wishlist_deal_notificationsWhereUniqueInput | Prisma.wishlist_deal_notificationsWhereUniqueInput[]
  delete?: Prisma.wishlist_deal_notificationsWhereUniqueInput | Prisma.wishlist_deal_notificationsWhereUniqueInput[]
  connect?: Prisma.wishlist_deal_notificationsWhereUniqueInput | Prisma.wishlist_deal_notificationsWhereUniqueInput[]
  update?: Prisma.wishlist_deal_notificationsUpdateWithWhereUniqueWithoutGamesInput | Prisma.wishlist_deal_notificationsUpdateWithWhereUniqueWithoutGamesInput[]
  updateMany?: Prisma.wishlist_deal_notificationsUpdateManyWithWhereWithoutGamesInput | Prisma.wishlist_deal_notificationsUpdateManyWithWhereWithoutGamesInput[]
  deleteMany?: Prisma.wishlist_deal_notificationsScalarWhereInput | Prisma.wishlist_deal_notificationsScalarWhereInput[]
}

export type wishlist_deal_notificationsCreateNestedManyWithoutDealsInput = {
  create?: Prisma.XOR<Prisma.wishlist_deal_notificationsCreateWithoutDealsInput, Prisma.wishlist_deal_notificationsUncheckedCreateWithoutDealsInput> | Prisma.wishlist_deal_notificationsCreateWithoutDealsInput[] | Prisma.wishlist_deal_notificationsUncheckedCreateWithoutDealsInput[]
  connectOrCreate?: Prisma.wishlist_deal_notificationsCreateOrConnectWithoutDealsInput | Prisma.wishlist_deal_notificationsCreateOrConnectWithoutDealsInput[]
  createMany?: Prisma.wishlist_deal_notificationsCreateManyDealsInputEnvelope
  connect?: Prisma.wishlist_deal_notificationsWhereUniqueInput | Prisma.wishlist_deal_notificationsWhereUniqueInput[]
}

export type wishlist_deal_notificationsUncheckedCreateNestedManyWithoutDealsInput = {
  create?: Prisma.XOR<Prisma.wishlist_deal_notificationsCreateWithoutDealsInput, Prisma.wishlist_deal_notificationsUncheckedCreateWithoutDealsInput> | Prisma.wishlist_deal_notificationsCreateWithoutDealsInput[] | Prisma.wishlist_deal_notificationsUncheckedCreateWithoutDealsInput[]
  connectOrCreate?: Prisma.wishlist_deal_notificationsCreateOrConnectWithoutDealsInput | Prisma.wishlist_deal_notificationsCreateOrConnectWithoutDealsInput[]
  createMany?: Prisma.wishlist_deal_notificationsCreateManyDealsInputEnvelope
  connect?: Prisma.wishlist_deal_notificationsWhereUniqueInput | Prisma.wishlist_deal_notificationsWhereUniqueInput[]
}

export type wishlist_deal_notificationsUpdateManyWithoutDealsNestedInput = {
  create?: Prisma.XOR<Prisma.wishlist_deal_notificationsCreateWithoutDealsInput, Prisma.wishlist_deal_notificationsUncheckedCreateWithoutDealsInput> | Prisma.wishlist_deal_notificationsCreateWithoutDealsInput[] | Prisma.wishlist_deal_notificationsUncheckedCreateWithoutDealsInput[]
  connectOrCreate?: Prisma.wishlist_deal_notificationsCreateOrConnectWithoutDealsInput | Prisma.wishlist_deal_notificationsCreateOrConnectWithoutDealsInput[]
  upsert?: Prisma.wishlist_deal_notificationsUpsertWithWhereUniqueWithoutDealsInput | Prisma.wishlist_deal_notificationsUpsertWithWhereUniqueWithoutDealsInput[]
  createMany?: Prisma.wishlist_deal_notificationsCreateManyDealsInputEnvelope
  set?: Prisma.wishlist_deal_notificationsWhereUniqueInput | Prisma.wishlist_deal_notificationsWhereUniqueInput[]
  disconnect?: Prisma.wishlist_deal_notificationsWhereUniqueInput | Prisma.wishlist_deal_notificationsWhereUniqueInput[]
  delete?: Prisma.wishlist_deal_notificationsWhereUniqueInput | Prisma.wishlist_deal_notificationsWhereUniqueInput[]
  connect?: Prisma.wishlist_deal_notificationsWhereUniqueInput | Prisma.wishlist_deal_notificationsWhereUniqueInput[]
  update?: Prisma.wishlist_deal_notificationsUpdateWithWhereUniqueWithoutDealsInput | Prisma.wishlist_deal_notificationsUpdateWithWhereUniqueWithoutDealsInput[]
  updateMany?: Prisma.wishlist_deal_notificationsUpdateManyWithWhereWithoutDealsInput | Prisma.wishlist_deal_notificationsUpdateManyWithWhereWithoutDealsInput[]
  deleteMany?: Prisma.wishlist_deal_notificationsScalarWhereInput | Prisma.wishlist_deal_notificationsScalarWhereInput[]
}

export type wishlist_deal_notificationsUncheckedUpdateManyWithoutDealsNestedInput = {
  create?: Prisma.XOR<Prisma.wishlist_deal_notificationsCreateWithoutDealsInput, Prisma.wishlist_deal_notificationsUncheckedCreateWithoutDealsInput> | Prisma.wishlist_deal_notificationsCreateWithoutDealsInput[] | Prisma.wishlist_deal_notificationsUncheckedCreateWithoutDealsInput[]
  connectOrCreate?: Prisma.wishlist_deal_notificationsCreateOrConnectWithoutDealsInput | Prisma.wishlist_deal_notificationsCreateOrConnectWithoutDealsInput[]
  upsert?: Prisma.wishlist_deal_notificationsUpsertWithWhereUniqueWithoutDealsInput | Prisma.wishlist_deal_notificationsUpsertWithWhereUniqueWithoutDealsInput[]
  createMany?: Prisma.wishlist_deal_notificationsCreateManyDealsInputEnvelope
  set?: Prisma.wishlist_deal_notificationsWhereUniqueInput | Prisma.wishlist_deal_notificationsWhereUniqueInput[]
  disconnect?: Prisma.wishlist_deal_notificationsWhereUniqueInput | Prisma.wishlist_deal_notificationsWhereUniqueInput[]
  delete?: Prisma.wishlist_deal_notificationsWhereUniqueInput | Prisma.wishlist_deal_notificationsWhereUniqueInput[]
  connect?: Prisma.wishlist_deal_notificationsWhereUniqueInput | Prisma.wishlist_deal_notificationsWhereUniqueInput[]
  update?: Prisma.wishlist_deal_notificationsUpdateWithWhereUniqueWithoutDealsInput | Prisma.wishlist_deal_notificationsUpdateWithWhereUniqueWithoutDealsInput[]
  updateMany?: Prisma.wishlist_deal_notificationsUpdateManyWithWhereWithoutDealsInput | Prisma.wishlist_deal_notificationsUpdateManyWithWhereWithoutDealsInput[]
  deleteMany?: Prisma.wishlist_deal_notificationsScalarWhereInput | Prisma.wishlist_deal_notificationsScalarWhereInput[]
}

export type wishlist_deal_notificationsCreateWithoutUsersInput = {
  notificationSent?: boolean
  createdAt?: Date | string
  updatedAt: Date | string
  deals: Prisma.DealCreateNestedOneWithoutWishlist_deal_notificationsInput
  games: Prisma.GameCreateNestedOneWithoutWishlist_deal_notificationsInput
}

export type wishlist_deal_notificationsUncheckedCreateWithoutUsersInput = {
  id?: number
  gameId: number
  dealId: number
  notificationSent?: boolean
  createdAt?: Date | string
  updatedAt: Date | string
}

export type wishlist_deal_notificationsCreateOrConnectWithoutUsersInput = {
  where: Prisma.wishlist_deal_notificationsWhereUniqueInput
  create: Prisma.XOR<Prisma.wishlist_deal_notificationsCreateWithoutUsersInput, Prisma.wishlist_deal_notificationsUncheckedCreateWithoutUsersInput>
}

export type wishlist_deal_notificationsCreateManyUsersInputEnvelope = {
  data: Prisma.wishlist_deal_notificationsCreateManyUsersInput | Prisma.wishlist_deal_notificationsCreateManyUsersInput[]
  skipDuplicates?: boolean
}

export type wishlist_deal_notificationsUpsertWithWhereUniqueWithoutUsersInput = {
  where: Prisma.wishlist_deal_notificationsWhereUniqueInput
  update: Prisma.XOR<Prisma.wishlist_deal_notificationsUpdateWithoutUsersInput, Prisma.wishlist_deal_notificationsUncheckedUpdateWithoutUsersInput>
  create: Prisma.XOR<Prisma.wishlist_deal_notificationsCreateWithoutUsersInput, Prisma.wishlist_deal_notificationsUncheckedCreateWithoutUsersInput>
}

export type wishlist_deal_notificationsUpdateWithWhereUniqueWithoutUsersInput = {
  where: Prisma.wishlist_deal_notificationsWhereUniqueInput
  data: Prisma.XOR<Prisma.wishlist_deal_notificationsUpdateWithoutUsersInput, Prisma.wishlist_deal_notificationsUncheckedUpdateWithoutUsersInput>
}

export type wishlist_deal_notificationsUpdateManyWithWhereWithoutUsersInput = {
  where: Prisma.wishlist_deal_notificationsScalarWhereInput
  data: Prisma.XOR<Prisma.wishlist_deal_notificationsUpdateManyMutationInput, Prisma.wishlist_deal_notificationsUncheckedUpdateManyWithoutUsersInput>
}

export type wishlist_deal_notificationsScalarWhereInput = {
  AND?: Prisma.wishlist_deal_notificationsScalarWhereInput | Prisma.wishlist_deal_notificationsScalarWhereInput[]
  OR?: Prisma.wishlist_deal_notificationsScalarWhereInput[]
  NOT?: Prisma.wishlist_deal_notificationsScalarWhereInput | Prisma.wishlist_deal_notificationsScalarWhereInput[]
  id?: Prisma.IntFilter<"wishlist_deal_notifications"> | number
  userId?: Prisma.IntFilter<"wishlist_deal_notifications"> | number
  gameId?: Prisma.IntFilter<"wishlist_deal_notifications"> | number
  dealId?: Prisma.IntFilter<"wishlist_deal_notifications"> | number
  notificationSent?: Prisma.BoolFilter<"wishlist_deal_notifications"> | boolean
  createdAt?: Prisma.DateTimeFilter<"wishlist_deal_notifications"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"wishlist_deal_notifications"> | Date | string
}

export type wishlist_deal_notificationsCreateWithoutGamesInput = {
  notificationSent?: boolean
  createdAt?: Date | string
  updatedAt: Date | string
  deals: Prisma.DealCreateNestedOneWithoutWishlist_deal_notificationsInput
  users: Prisma.UserCreateNestedOneWithoutWishlist_deal_notificationsInput
}

export type wishlist_deal_notificationsUncheckedCreateWithoutGamesInput = {
  id?: number
  userId: number
  dealId: number
  notificationSent?: boolean
  createdAt?: Date | string
  updatedAt: Date | string
}

export type wishlist_deal_notificationsCreateOrConnectWithoutGamesInput = {
  where: Prisma.wishlist_deal_notificationsWhereUniqueInput
  create: Prisma.XOR<Prisma.wishlist_deal_notificationsCreateWithoutGamesInput, Prisma.wishlist_deal_notificationsUncheckedCreateWithoutGamesInput>
}

export type wishlist_deal_notificationsCreateManyGamesInputEnvelope = {
  data: Prisma.wishlist_deal_notificationsCreateManyGamesInput | Prisma.wishlist_deal_notificationsCreateManyGamesInput[]
  skipDuplicates?: boolean
}

export type wishlist_deal_notificationsUpsertWithWhereUniqueWithoutGamesInput = {
  where: Prisma.wishlist_deal_notificationsWhereUniqueInput
  update: Prisma.XOR<Prisma.wishlist_deal_notificationsUpdateWithoutGamesInput, Prisma.wishlist_deal_notificationsUncheckedUpdateWithoutGamesInput>
  create: Prisma.XOR<Prisma.wishlist_deal_notificationsCreateWithoutGamesInput, Prisma.wishlist_deal_notificationsUncheckedCreateWithoutGamesInput>
}

export type wishlist_deal_notificationsUpdateWithWhereUniqueWithoutGamesInput = {
  where: Prisma.wishlist_deal_notificationsWhereUniqueInput
  data: Prisma.XOR<Prisma.wishlist_deal_notificationsUpdateWithoutGamesInput, Prisma.wishlist_deal_notificationsUncheckedUpdateWithoutGamesInput>
}

export type wishlist_deal_notificationsUpdateManyWithWhereWithoutGamesInput = {
  where: Prisma.wishlist_deal_notificationsScalarWhereInput
  data: Prisma.XOR<Prisma.wishlist_deal_notificationsUpdateManyMutationInput, Prisma.wishlist_deal_notificationsUncheckedUpdateManyWithoutGamesInput>
}

export type wishlist_deal_notificationsCreateWithoutDealsInput = {
  notificationSent?: boolean
  createdAt?: Date | string
  updatedAt: Date | string
  games: Prisma.GameCreateNestedOneWithoutWishlist_deal_notificationsInput
  users: Prisma.UserCreateNestedOneWithoutWishlist_deal_notificationsInput
}

export type wishlist_deal_notificationsUncheckedCreateWithoutDealsInput = {
  id?: number
  userId: number
  gameId: number
  notificationSent?: boolean
  createdAt?: Date | string
  updatedAt: Date | string
}

export type wishlist_deal_notificationsCreateOrConnectWithoutDealsInput = {
  where: Prisma.wishlist_deal_notificationsWhereUniqueInput
  create: Prisma.XOR<Prisma.wishlist_deal_notificationsCreateWithoutDealsInput, Prisma.wishlist_deal_notificationsUncheckedCreateWithoutDealsInput>
}

export type wishlist_deal_notificationsCreateManyDealsInputEnvelope = {
  data: Prisma.wishlist_deal_notificationsCreateManyDealsInput | Prisma.wishlist_deal_notificationsCreateManyDealsInput[]
  skipDuplicates?: boolean
}

export type wishlist_deal_notificationsUpsertWithWhereUniqueWithoutDealsInput = {
  where: Prisma.wishlist_deal_notificationsWhereUniqueInput
  update: Prisma.XOR<Prisma.wishlist_deal_notificationsUpdateWithoutDealsInput, Prisma.wishlist_deal_notificationsUncheckedUpdateWithoutDealsInput>
  create: Prisma.XOR<Prisma.wishlist_deal_notificationsCreateWithoutDealsInput, Prisma.wishlist_deal_notificationsUncheckedCreateWithoutDealsInput>
}

export type wishlist_deal_notificationsUpdateWithWhereUniqueWithoutDealsInput = {
  where: Prisma.wishlist_deal_notificationsWhereUniqueInput
  data: Prisma.XOR<Prisma.wishlist_deal_notificationsUpdateWithoutDealsInput, Prisma.wishlist_deal_notificationsUncheckedUpdateWithoutDealsInput>
}

export type wishlist_deal_notificationsUpdateManyWithWhereWithoutDealsInput = {
  where: Prisma.wishlist_deal_notificationsScalarWhereInput
  data: Prisma.XOR<Prisma.wishlist_deal_notificationsUpdateManyMutationInput, Prisma.wishlist_deal_notificationsUncheckedUpdateManyWithoutDealsInput>
}

export type wishlist_deal_notificationsCreateManyUsersInput = {
  id?: number
  gameId: number
  dealId: number
  notificationSent?: boolean
  createdAt?: Date | string
  updatedAt: Date | string
}

export type wishlist_deal_notificationsUpdateWithoutUsersInput = {
  notificationSent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deals?: Prisma.DealUpdateOneRequiredWithoutWishlist_deal_notificationsNestedInput
  games?: Prisma.GameUpdateOneRequiredWithoutWishlist_deal_notificationsNestedInput
}

export type wishlist_deal_notificationsUncheckedUpdateWithoutUsersInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  gameId?: Prisma.IntFieldUpdateOperationsInput | number
  dealId?: Prisma.IntFieldUpdateOperationsInput | number
  notificationSent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type wishlist_deal_notificationsUncheckedUpdateManyWithoutUsersInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  gameId?: Prisma.IntFieldUpdateOperationsInput | number
  dealId?: Prisma.IntFieldUpdateOperationsInput | number
  notificationSent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type wishlist_deal_notificationsCreateManyGamesInput = {
  id?: number
  userId: number
  dealId: number
  notificationSent?: boolean
  createdAt?: Date | string
  updatedAt: Date | string
}

export type wishlist_deal_notificationsUpdateWithoutGamesInput = {
  notificationSent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deals?: Prisma.DealUpdateOneRequiredWithoutWishlist_deal_notificationsNestedInput
  users?: Prisma.UserUpdateOneRequiredWithoutWishlist_deal_notificationsNestedInput
}

export type wishlist_deal_notificationsUncheckedUpdateWithoutGamesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  dealId?: Prisma.IntFieldUpdateOperationsInput | number
  notificationSent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type wishlist_deal_notificationsUncheckedUpdateManyWithoutGamesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  dealId?: Prisma.IntFieldUpdateOperationsInput | number
  notificationSent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type wishlist_deal_notificationsCreateManyDealsInput = {
  id?: number
  userId: number
  gameId: number
  notificationSent?: boolean
  createdAt?: Date | string
  updatedAt: Date | string
}

export type wishlist_deal_notificationsUpdateWithoutDealsInput = {
  notificationSent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  games?: Prisma.GameUpdateOneRequiredWithoutWishlist_deal_notificationsNestedInput
  users?: Prisma.UserUpdateOneRequiredWithoutWishlist_deal_notificationsNestedInput
}

export type wishlist_deal_notificationsUncheckedUpdateWithoutDealsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  gameId?: Prisma.IntFieldUpdateOperationsInput | number
  notificationSent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type wishlist_deal_notificationsUncheckedUpdateManyWithoutDealsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.IntFieldUpdateOperationsInput | number
  gameId?: Prisma.IntFieldUpdateOperationsInput | number
  notificationSent?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type wishlist_deal_notificationsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  gameId?: boolean
  dealId?: boolean
  notificationSent?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deals?: boolean | Prisma.DealDefaultArgs<ExtArgs>
  games?: boolean | Prisma.GameDefaultArgs<ExtArgs>
  users?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["wishlist_deal_notifications"]>

export type wishlist_deal_notificationsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  gameId?: boolean
  dealId?: boolean
  notificationSent?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deals?: boolean | Prisma.DealDefaultArgs<ExtArgs>
  games?: boolean | Prisma.GameDefaultArgs<ExtArgs>
  users?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["wishlist_deal_notifications"]>

export type wishlist_deal_notificationsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  gameId?: boolean
  dealId?: boolean
  notificationSent?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deals?: boolean | Prisma.DealDefaultArgs<ExtArgs>
  games?: boolean | Prisma.GameDefaultArgs<ExtArgs>
  users?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["wishlist_deal_notifications"]>

export type wishlist_deal_notificationsSelectScalar = {
  id?: boolean
  userId?: boolean
  gameId?: boolean
  dealId?: boolean
  notificationSent?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type wishlist_deal_notificationsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "gameId" | "dealId" | "notificationSent" | "createdAt" | "updatedAt", ExtArgs["result"]["wishlist_deal_notifications"]>
export type wishlist_deal_notificationsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  deals?: boolean | Prisma.DealDefaultArgs<ExtArgs>
  games?: boolean | Prisma.GameDefaultArgs<ExtArgs>
  users?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type wishlist_deal_notificationsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  deals?: boolean | Prisma.DealDefaultArgs<ExtArgs>
  games?: boolean | Prisma.GameDefaultArgs<ExtArgs>
  users?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type wishlist_deal_notificationsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  deals?: boolean | Prisma.DealDefaultArgs<ExtArgs>
  games?: boolean | Prisma.GameDefaultArgs<ExtArgs>
  users?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $wishlist_deal_notificationsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "wishlist_deal_notifications"
  objects: {
    deals: Prisma.$DealPayload<ExtArgs>
    games: Prisma.$GamePayload<ExtArgs>
    users: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    userId: number
    gameId: number
    dealId: number
    notificationSent: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["wishlist_deal_notifications"]>
  composites: {}
}

export type wishlist_deal_notificationsGetPayload<S extends boolean | null | undefined | wishlist_deal_notificationsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$wishlist_deal_notificationsPayload, S>

export type wishlist_deal_notificationsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<wishlist_deal_notificationsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Wishlist_deal_notificationsCountAggregateInputType | true
  }

export interface wishlist_deal_notificationsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['wishlist_deal_notifications'], meta: { name: 'wishlist_deal_notifications' } }
  /**
   * Find zero or one Wishlist_deal_notifications that matches the filter.
   * @param {wishlist_deal_notificationsFindUniqueArgs} args - Arguments to find a Wishlist_deal_notifications
   * @example
   * // Get one Wishlist_deal_notifications
   * const wishlist_deal_notifications = await prisma.wishlist_deal_notifications.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends wishlist_deal_notificationsFindUniqueArgs>(args: Prisma.SelectSubset<T, wishlist_deal_notificationsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__wishlist_deal_notificationsClient<runtime.Types.Result.GetResult<Prisma.$wishlist_deal_notificationsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Wishlist_deal_notifications that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {wishlist_deal_notificationsFindUniqueOrThrowArgs} args - Arguments to find a Wishlist_deal_notifications
   * @example
   * // Get one Wishlist_deal_notifications
   * const wishlist_deal_notifications = await prisma.wishlist_deal_notifications.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends wishlist_deal_notificationsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, wishlist_deal_notificationsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__wishlist_deal_notificationsClient<runtime.Types.Result.GetResult<Prisma.$wishlist_deal_notificationsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Wishlist_deal_notifications that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {wishlist_deal_notificationsFindFirstArgs} args - Arguments to find a Wishlist_deal_notifications
   * @example
   * // Get one Wishlist_deal_notifications
   * const wishlist_deal_notifications = await prisma.wishlist_deal_notifications.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends wishlist_deal_notificationsFindFirstArgs>(args?: Prisma.SelectSubset<T, wishlist_deal_notificationsFindFirstArgs<ExtArgs>>): Prisma.Prisma__wishlist_deal_notificationsClient<runtime.Types.Result.GetResult<Prisma.$wishlist_deal_notificationsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Wishlist_deal_notifications that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {wishlist_deal_notificationsFindFirstOrThrowArgs} args - Arguments to find a Wishlist_deal_notifications
   * @example
   * // Get one Wishlist_deal_notifications
   * const wishlist_deal_notifications = await prisma.wishlist_deal_notifications.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends wishlist_deal_notificationsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, wishlist_deal_notificationsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__wishlist_deal_notificationsClient<runtime.Types.Result.GetResult<Prisma.$wishlist_deal_notificationsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Wishlist_deal_notifications that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {wishlist_deal_notificationsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Wishlist_deal_notifications
   * const wishlist_deal_notifications = await prisma.wishlist_deal_notifications.findMany()
   * 
   * // Get first 10 Wishlist_deal_notifications
   * const wishlist_deal_notifications = await prisma.wishlist_deal_notifications.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const wishlist_deal_notificationsWithIdOnly = await prisma.wishlist_deal_notifications.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends wishlist_deal_notificationsFindManyArgs>(args?: Prisma.SelectSubset<T, wishlist_deal_notificationsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$wishlist_deal_notificationsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Wishlist_deal_notifications.
   * @param {wishlist_deal_notificationsCreateArgs} args - Arguments to create a Wishlist_deal_notifications.
   * @example
   * // Create one Wishlist_deal_notifications
   * const Wishlist_deal_notifications = await prisma.wishlist_deal_notifications.create({
   *   data: {
   *     // ... data to create a Wishlist_deal_notifications
   *   }
   * })
   * 
   */
  create<T extends wishlist_deal_notificationsCreateArgs>(args: Prisma.SelectSubset<T, wishlist_deal_notificationsCreateArgs<ExtArgs>>): Prisma.Prisma__wishlist_deal_notificationsClient<runtime.Types.Result.GetResult<Prisma.$wishlist_deal_notificationsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Wishlist_deal_notifications.
   * @param {wishlist_deal_notificationsCreateManyArgs} args - Arguments to create many Wishlist_deal_notifications.
   * @example
   * // Create many Wishlist_deal_notifications
   * const wishlist_deal_notifications = await prisma.wishlist_deal_notifications.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends wishlist_deal_notificationsCreateManyArgs>(args?: Prisma.SelectSubset<T, wishlist_deal_notificationsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Wishlist_deal_notifications and returns the data saved in the database.
   * @param {wishlist_deal_notificationsCreateManyAndReturnArgs} args - Arguments to create many Wishlist_deal_notifications.
   * @example
   * // Create many Wishlist_deal_notifications
   * const wishlist_deal_notifications = await prisma.wishlist_deal_notifications.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Wishlist_deal_notifications and only return the `id`
   * const wishlist_deal_notificationsWithIdOnly = await prisma.wishlist_deal_notifications.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends wishlist_deal_notificationsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, wishlist_deal_notificationsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$wishlist_deal_notificationsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Wishlist_deal_notifications.
   * @param {wishlist_deal_notificationsDeleteArgs} args - Arguments to delete one Wishlist_deal_notifications.
   * @example
   * // Delete one Wishlist_deal_notifications
   * const Wishlist_deal_notifications = await prisma.wishlist_deal_notifications.delete({
   *   where: {
   *     // ... filter to delete one Wishlist_deal_notifications
   *   }
   * })
   * 
   */
  delete<T extends wishlist_deal_notificationsDeleteArgs>(args: Prisma.SelectSubset<T, wishlist_deal_notificationsDeleteArgs<ExtArgs>>): Prisma.Prisma__wishlist_deal_notificationsClient<runtime.Types.Result.GetResult<Prisma.$wishlist_deal_notificationsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Wishlist_deal_notifications.
   * @param {wishlist_deal_notificationsUpdateArgs} args - Arguments to update one Wishlist_deal_notifications.
   * @example
   * // Update one Wishlist_deal_notifications
   * const wishlist_deal_notifications = await prisma.wishlist_deal_notifications.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends wishlist_deal_notificationsUpdateArgs>(args: Prisma.SelectSubset<T, wishlist_deal_notificationsUpdateArgs<ExtArgs>>): Prisma.Prisma__wishlist_deal_notificationsClient<runtime.Types.Result.GetResult<Prisma.$wishlist_deal_notificationsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Wishlist_deal_notifications.
   * @param {wishlist_deal_notificationsDeleteManyArgs} args - Arguments to filter Wishlist_deal_notifications to delete.
   * @example
   * // Delete a few Wishlist_deal_notifications
   * const { count } = await prisma.wishlist_deal_notifications.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends wishlist_deal_notificationsDeleteManyArgs>(args?: Prisma.SelectSubset<T, wishlist_deal_notificationsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Wishlist_deal_notifications.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {wishlist_deal_notificationsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Wishlist_deal_notifications
   * const wishlist_deal_notifications = await prisma.wishlist_deal_notifications.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends wishlist_deal_notificationsUpdateManyArgs>(args: Prisma.SelectSubset<T, wishlist_deal_notificationsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Wishlist_deal_notifications and returns the data updated in the database.
   * @param {wishlist_deal_notificationsUpdateManyAndReturnArgs} args - Arguments to update many Wishlist_deal_notifications.
   * @example
   * // Update many Wishlist_deal_notifications
   * const wishlist_deal_notifications = await prisma.wishlist_deal_notifications.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Wishlist_deal_notifications and only return the `id`
   * const wishlist_deal_notificationsWithIdOnly = await prisma.wishlist_deal_notifications.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends wishlist_deal_notificationsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, wishlist_deal_notificationsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$wishlist_deal_notificationsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Wishlist_deal_notifications.
   * @param {wishlist_deal_notificationsUpsertArgs} args - Arguments to update or create a Wishlist_deal_notifications.
   * @example
   * // Update or create a Wishlist_deal_notifications
   * const wishlist_deal_notifications = await prisma.wishlist_deal_notifications.upsert({
   *   create: {
   *     // ... data to create a Wishlist_deal_notifications
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Wishlist_deal_notifications we want to update
   *   }
   * })
   */
  upsert<T extends wishlist_deal_notificationsUpsertArgs>(args: Prisma.SelectSubset<T, wishlist_deal_notificationsUpsertArgs<ExtArgs>>): Prisma.Prisma__wishlist_deal_notificationsClient<runtime.Types.Result.GetResult<Prisma.$wishlist_deal_notificationsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Wishlist_deal_notifications.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {wishlist_deal_notificationsCountArgs} args - Arguments to filter Wishlist_deal_notifications to count.
   * @example
   * // Count the number of Wishlist_deal_notifications
   * const count = await prisma.wishlist_deal_notifications.count({
   *   where: {
   *     // ... the filter for the Wishlist_deal_notifications we want to count
   *   }
   * })
  **/
  count<T extends wishlist_deal_notificationsCountArgs>(
    args?: Prisma.Subset<T, wishlist_deal_notificationsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Wishlist_deal_notificationsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Wishlist_deal_notifications.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Wishlist_deal_notificationsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Wishlist_deal_notificationsAggregateArgs>(args: Prisma.Subset<T, Wishlist_deal_notificationsAggregateArgs>): Prisma.PrismaPromise<GetWishlist_deal_notificationsAggregateType<T>>

  /**
   * Group by Wishlist_deal_notifications.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {wishlist_deal_notificationsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends wishlist_deal_notificationsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: wishlist_deal_notificationsGroupByArgs['orderBy'] }
      : { orderBy?: wishlist_deal_notificationsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, wishlist_deal_notificationsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetWishlist_deal_notificationsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the wishlist_deal_notifications model
 */
readonly fields: wishlist_deal_notificationsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for wishlist_deal_notifications.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__wishlist_deal_notificationsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  deals<T extends Prisma.DealDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DealDefaultArgs<ExtArgs>>): Prisma.Prisma__DealClient<runtime.Types.Result.GetResult<Prisma.$DealPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  games<T extends Prisma.GameDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.GameDefaultArgs<ExtArgs>>): Prisma.Prisma__GameClient<runtime.Types.Result.GetResult<Prisma.$GamePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  users<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the wishlist_deal_notifications model
 */
export interface wishlist_deal_notificationsFieldRefs {
  readonly id: Prisma.FieldRef<"wishlist_deal_notifications", 'Int'>
  readonly userId: Prisma.FieldRef<"wishlist_deal_notifications", 'Int'>
  readonly gameId: Prisma.FieldRef<"wishlist_deal_notifications", 'Int'>
  readonly dealId: Prisma.FieldRef<"wishlist_deal_notifications", 'Int'>
  readonly notificationSent: Prisma.FieldRef<"wishlist_deal_notifications", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"wishlist_deal_notifications", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"wishlist_deal_notifications", 'DateTime'>
}
    

// Custom InputTypes
/**
 * wishlist_deal_notifications findUnique
 */
export type wishlist_deal_notificationsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_deal_notifications
   */
  select?: Prisma.wishlist_deal_notificationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_deal_notifications
   */
  omit?: Prisma.wishlist_deal_notificationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_deal_notificationsInclude<ExtArgs> | null
  /**
   * Filter, which wishlist_deal_notifications to fetch.
   */
  where: Prisma.wishlist_deal_notificationsWhereUniqueInput
}

/**
 * wishlist_deal_notifications findUniqueOrThrow
 */
export type wishlist_deal_notificationsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_deal_notifications
   */
  select?: Prisma.wishlist_deal_notificationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_deal_notifications
   */
  omit?: Prisma.wishlist_deal_notificationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_deal_notificationsInclude<ExtArgs> | null
  /**
   * Filter, which wishlist_deal_notifications to fetch.
   */
  where: Prisma.wishlist_deal_notificationsWhereUniqueInput
}

/**
 * wishlist_deal_notifications findFirst
 */
export type wishlist_deal_notificationsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_deal_notifications
   */
  select?: Prisma.wishlist_deal_notificationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_deal_notifications
   */
  omit?: Prisma.wishlist_deal_notificationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_deal_notificationsInclude<ExtArgs> | null
  /**
   * Filter, which wishlist_deal_notifications to fetch.
   */
  where?: Prisma.wishlist_deal_notificationsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of wishlist_deal_notifications to fetch.
   */
  orderBy?: Prisma.wishlist_deal_notificationsOrderByWithRelationInput | Prisma.wishlist_deal_notificationsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for wishlist_deal_notifications.
   */
  cursor?: Prisma.wishlist_deal_notificationsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` wishlist_deal_notifications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` wishlist_deal_notifications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of wishlist_deal_notifications.
   */
  distinct?: Prisma.Wishlist_deal_notificationsScalarFieldEnum | Prisma.Wishlist_deal_notificationsScalarFieldEnum[]
}

/**
 * wishlist_deal_notifications findFirstOrThrow
 */
export type wishlist_deal_notificationsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_deal_notifications
   */
  select?: Prisma.wishlist_deal_notificationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_deal_notifications
   */
  omit?: Prisma.wishlist_deal_notificationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_deal_notificationsInclude<ExtArgs> | null
  /**
   * Filter, which wishlist_deal_notifications to fetch.
   */
  where?: Prisma.wishlist_deal_notificationsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of wishlist_deal_notifications to fetch.
   */
  orderBy?: Prisma.wishlist_deal_notificationsOrderByWithRelationInput | Prisma.wishlist_deal_notificationsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for wishlist_deal_notifications.
   */
  cursor?: Prisma.wishlist_deal_notificationsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` wishlist_deal_notifications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` wishlist_deal_notifications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of wishlist_deal_notifications.
   */
  distinct?: Prisma.Wishlist_deal_notificationsScalarFieldEnum | Prisma.Wishlist_deal_notificationsScalarFieldEnum[]
}

/**
 * wishlist_deal_notifications findMany
 */
export type wishlist_deal_notificationsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_deal_notifications
   */
  select?: Prisma.wishlist_deal_notificationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_deal_notifications
   */
  omit?: Prisma.wishlist_deal_notificationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_deal_notificationsInclude<ExtArgs> | null
  /**
   * Filter, which wishlist_deal_notifications to fetch.
   */
  where?: Prisma.wishlist_deal_notificationsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of wishlist_deal_notifications to fetch.
   */
  orderBy?: Prisma.wishlist_deal_notificationsOrderByWithRelationInput | Prisma.wishlist_deal_notificationsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing wishlist_deal_notifications.
   */
  cursor?: Prisma.wishlist_deal_notificationsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` wishlist_deal_notifications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` wishlist_deal_notifications.
   */
  skip?: number
  distinct?: Prisma.Wishlist_deal_notificationsScalarFieldEnum | Prisma.Wishlist_deal_notificationsScalarFieldEnum[]
}

/**
 * wishlist_deal_notifications create
 */
export type wishlist_deal_notificationsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_deal_notifications
   */
  select?: Prisma.wishlist_deal_notificationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_deal_notifications
   */
  omit?: Prisma.wishlist_deal_notificationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_deal_notificationsInclude<ExtArgs> | null
  /**
   * The data needed to create a wishlist_deal_notifications.
   */
  data: Prisma.XOR<Prisma.wishlist_deal_notificationsCreateInput, Prisma.wishlist_deal_notificationsUncheckedCreateInput>
}

/**
 * wishlist_deal_notifications createMany
 */
export type wishlist_deal_notificationsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many wishlist_deal_notifications.
   */
  data: Prisma.wishlist_deal_notificationsCreateManyInput | Prisma.wishlist_deal_notificationsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * wishlist_deal_notifications createManyAndReturn
 */
export type wishlist_deal_notificationsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_deal_notifications
   */
  select?: Prisma.wishlist_deal_notificationsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_deal_notifications
   */
  omit?: Prisma.wishlist_deal_notificationsOmit<ExtArgs> | null
  /**
   * The data used to create many wishlist_deal_notifications.
   */
  data: Prisma.wishlist_deal_notificationsCreateManyInput | Prisma.wishlist_deal_notificationsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_deal_notificationsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * wishlist_deal_notifications update
 */
export type wishlist_deal_notificationsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_deal_notifications
   */
  select?: Prisma.wishlist_deal_notificationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_deal_notifications
   */
  omit?: Prisma.wishlist_deal_notificationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_deal_notificationsInclude<ExtArgs> | null
  /**
   * The data needed to update a wishlist_deal_notifications.
   */
  data: Prisma.XOR<Prisma.wishlist_deal_notificationsUpdateInput, Prisma.wishlist_deal_notificationsUncheckedUpdateInput>
  /**
   * Choose, which wishlist_deal_notifications to update.
   */
  where: Prisma.wishlist_deal_notificationsWhereUniqueInput
}

/**
 * wishlist_deal_notifications updateMany
 */
export type wishlist_deal_notificationsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update wishlist_deal_notifications.
   */
  data: Prisma.XOR<Prisma.wishlist_deal_notificationsUpdateManyMutationInput, Prisma.wishlist_deal_notificationsUncheckedUpdateManyInput>
  /**
   * Filter which wishlist_deal_notifications to update
   */
  where?: Prisma.wishlist_deal_notificationsWhereInput
  /**
   * Limit how many wishlist_deal_notifications to update.
   */
  limit?: number
}

/**
 * wishlist_deal_notifications updateManyAndReturn
 */
export type wishlist_deal_notificationsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_deal_notifications
   */
  select?: Prisma.wishlist_deal_notificationsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_deal_notifications
   */
  omit?: Prisma.wishlist_deal_notificationsOmit<ExtArgs> | null
  /**
   * The data used to update wishlist_deal_notifications.
   */
  data: Prisma.XOR<Prisma.wishlist_deal_notificationsUpdateManyMutationInput, Prisma.wishlist_deal_notificationsUncheckedUpdateManyInput>
  /**
   * Filter which wishlist_deal_notifications to update
   */
  where?: Prisma.wishlist_deal_notificationsWhereInput
  /**
   * Limit how many wishlist_deal_notifications to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_deal_notificationsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * wishlist_deal_notifications upsert
 */
export type wishlist_deal_notificationsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_deal_notifications
   */
  select?: Prisma.wishlist_deal_notificationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_deal_notifications
   */
  omit?: Prisma.wishlist_deal_notificationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_deal_notificationsInclude<ExtArgs> | null
  /**
   * The filter to search for the wishlist_deal_notifications to update in case it exists.
   */
  where: Prisma.wishlist_deal_notificationsWhereUniqueInput
  /**
   * In case the wishlist_deal_notifications found by the `where` argument doesn't exist, create a new wishlist_deal_notifications with this data.
   */
  create: Prisma.XOR<Prisma.wishlist_deal_notificationsCreateInput, Prisma.wishlist_deal_notificationsUncheckedCreateInput>
  /**
   * In case the wishlist_deal_notifications was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.wishlist_deal_notificationsUpdateInput, Prisma.wishlist_deal_notificationsUncheckedUpdateInput>
}

/**
 * wishlist_deal_notifications delete
 */
export type wishlist_deal_notificationsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_deal_notifications
   */
  select?: Prisma.wishlist_deal_notificationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_deal_notifications
   */
  omit?: Prisma.wishlist_deal_notificationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_deal_notificationsInclude<ExtArgs> | null
  /**
   * Filter which wishlist_deal_notifications to delete.
   */
  where: Prisma.wishlist_deal_notificationsWhereUniqueInput
}

/**
 * wishlist_deal_notifications deleteMany
 */
export type wishlist_deal_notificationsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which wishlist_deal_notifications to delete
   */
  where?: Prisma.wishlist_deal_notificationsWhereInput
  /**
   * Limit how many wishlist_deal_notifications to delete.
   */
  limit?: number
}

/**
 * wishlist_deal_notifications without action
 */
export type wishlist_deal_notificationsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the wishlist_deal_notifications
   */
  select?: Prisma.wishlist_deal_notificationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the wishlist_deal_notifications
   */
  omit?: Prisma.wishlist_deal_notificationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.wishlist_deal_notificationsInclude<ExtArgs> | null
}
